<?php

$lang = array(
	'antivirus'	=> '杀毒',
    'msg_antivir_status'	=> '不起作用',
    'msg_antivir_err_login'	=> '您没有足够的权限访问此页面',
    'msg_antivir_folder_not_faund'	=> '目录不存在',
    'msg_antivir_err_process'	=> '执行错误，最后一行执行：',
    'msg_antivir_ok_process'	=> '处理成功',

    'tpl_antivir_common'	=> '常规信息',
    'tpl_antivir_check_folder'	=> '检查目录',
    'tpl_antivir_setting'	=> '设置',
    'tpl_antivir_install'	=> '安装防病毒软件',
    'tpl_antivir_auto_del'	=> '自动删除',
    'tpl_antivir_auto_isolation'	=> '自动隔离',
    'tpl_antivir_scan'	    => '扫描',
    'tpl_antivir_more'	    => '更多信息',
    'tpl_antivir_hidden'	=> '隐藏',
    'tpl_antivir_log_scan'	=> '扫描历史记录',
    'tpl_antivir_show_file'	=> '显示文件',
    'tpl_antivir_settingss'	=> '设置',
    'tpl_antivir_auto_update_db'	=> '自动更新反病毒数据库',
    'tpl_antivir_last_update'	=> '最后更新',
    'tpl_antivir_save'	    => '保存',
    'tpl_antivir_update'	=> '刷新',
    'tpl_antivir_more'	    => '更多信息',
    'tpl_antivir_hidden'	=> '隐藏',

    'tpl_antivir_go_process'	=> '进程正在进行中，请稍等',
    'tpl_antivir_begin_process'	=> '扫描进程正在进行中，请稍等',
    'tpl_antivir_save_conf'	=> '保存设置',
    'antivirus_not_root'	=> '您没有足够的权限',
    'antivirus_scan_susspend'	=> '扫描完成',
    'antivirus_scan_nosusspend'	=> '扫描失败',
    'antivirus_scan_check'	=> '请求已完成',
    'antivirus_scan_histiry'	=> '扫描历史记录',
    'antivirus_scan_histiry_null'	=> '扫描历史数组为空',
    'antivirus_not_data'	=> '文件为空',
    'antivirus_not_id_history'	=> '没有这样的历史记录',
    'antivirus_not_root1'	=> '你没有足够的权限',
    'antivirus_update_susspend'	=> '更新成功',
    'antivirus_update_nosusspend'	=> '更新失败',
    'antivirus_update_limit'	=> '更新超时',
    'antivirus_clear_history'	=> '删除扫描历史记录',
    'antivirus_run_clear_history'	=> '正在删除历史记录',
    'antivirus_clear_history_sus'	=> '已删除历史记录',
    'antivirus_move_carantyn'	=> '移到隔离区',
    'antivirus_delete'	=> '已删除',
    'antivirus_searche_bad_files'	=> '找到感染文件：',
    'antivirus_virus'	=> '病毒',
    'antivirus_karantine'	=> '隔离',
    'antivirus_delete_qw'	=> '删除',
    'antivirus_all'	=> '全部',
    'antivirus_delete_all'	=> '全部删除',
    'antivirus_file'	=> '文件',
    'antivirus_karantine_all'	=> '隔离所有',
    'antivirus_karantine_out'	=> '隔离',
    'antivirus_perfom'	=> '运行',
    'antivirus_path_karantine'	=> '隔离路径：',
    'antivirus_no_history'	=> '历史记录是空的',
    'antivirus_not_install'	=> '服务未安装',
    'antivirus_stopscan'	=> '停止',
    'antivirus_checkrunprocess'	=> '检查正在运行的进程...',
    'antivirus_processrun'	=> '正在搜索...',
    'antivirus_scan_terminate'	=> '扫描中断',
    'antivirus_update_start1'	=> '开始更新',
    'antivirus_update_finish1'	=> '更新完成',
);

?>