<?php

$lang = array (
	'apacserver' => '网络服务器管理',
	'directory_password' => '设置目录的密码',
	'apacserver_pass_selectdom' => '选择域名',
	'apacserver_pass_nodominacc' => '首先，您需要向帐户添加域名',
	'apacserver_dir_safe' => '目录不存在或格式无效',
	'apacserver_pass_safe' => '弱密码',
	'apacserver_add_dir_failed_already_exist' => '此文件夹的密码已经存在。',
	'apacserver_add_www_redir_ok' => '重新导向成功添加',
	'apacserver_delete_www_redir_ok' => '重定向成功删除',
	'apacserver_add_www_failed_exist' => '这种类型的重定向已经存在。',
	'apacserver_add_www_failed_bad_from' => '网站名称格式无效',
	'apacserver_add_www_failed_bad_to' => '目标格式无效',
	'apacserver_add_www_failed_not_perm' => '没有此操作的权限！',
	'apacserver_add_http_failed_exist' => '此网站的重定向已存在。',
	'apacserver_add_http_redir_ok' => '重新导向成功添加',
	'apacserver_delete_http_redir_ok' => '成功删除转发',

	'tpl_apac_delete' 	=> '删除',
	'msg_apac_ok'       => '成功',
	'msg_apac_not_perm' 	=> '未完成',

	'tpl_apac_jmp_site'     => '转发网站',
	'tpl_apac_add_site'     => '添加网站',
	'tpl_apac_site'     => '网站',
	'tpl_apac_www'      => 'www',
	'tpl_apac_nowww'    => '没有www',
	'tpl_apac_both'     => '两个',
	'tpl_apac_pattern'  => '按模式',
	'tpl_apac_destination' 	=> '分配',
	'tpl_apac_add_jpm'  => '请稍等,转发正在添加...',
	'tpl_apac_forwarding'   => '转发',
	'tpl_apac_forwarding_listhttp' 	=> '重定向列表',
	'tpl_apac_action_list'  => '网站、用户、目的地、转发、操作',

	'tpl_apac_user' 	=> '用户',
	'tpl_apac_action'   => '操作',

	'tpl_apac_jmp_far'  => 'HTTP重定向 - HTTPS',
	'tpl_apac_add_folder' 	=> '将密码设置为目录',
	'tpl_apac_jmp_type'     => '重定向类型',
	'tpl_apac_select_http'  => 'http转到http',
	'tpl_apac_select_https' 	=>'http转到https',
	'tpl_apac_folders' 	=> '个目录',
	'tpl_apac_folder'   => '目录',
	'tpl_apac_action_list1' 	=> '网站、用户、重定向、操作',
	'tpl_apac_action_list2'     => '目录、用户、密码、操作',

	'tpl_apac_set_pass_folder'  => '设置目录的密码',
	'tpl_apac_passwd' 	=> '密码',
	'tpl_apac_nopass_folder'    => '没有为任何文件夹设置密码',

	'tpl_apac_select_www'       => '转到www',
	'tpl_apac_select_nowww'     => '转到',
	'tpl_apac_jmp_www' 	=> 'WWW重定向',


	'js_apac_jmp_table' 	=> '该表格已包含此网站的批量转发',
	'js_apac_add_domain'    => '您需要向您的帐户添加域名',
	'apacserver_list_directory' 	=>'注册目录列表',
	'apacserver_list_not_directory' 	=>'受密码保护的目录列表为空',
	'apacserver_list_http' => '域名列表',
	'apacserver_none_list_http' => '域名列表为空',
	'apacserver_list_directory_http' => '目录列表',
	'apacserver_none_list_directory_http' => '目录列表为空',
	'apacserver_not_remove' => '这不是你的',
	'apacserver_not_type' => '不存在类型',
	'apacserver_list_forwarding' => '重定向列表',
	'apacserver_not_list_forwarding' => '重定向列表为空',
	'apacserver_not_unic_id' => 'unic_id输入不正确。或者这种重定向不再存在',
	'apacserver_not_domain' => '不是现有的域名',
	'apacserver_not_forward' => '转发分配无效',
	'apacserver_not_path_forward' => '没有指定转发路径',
	'apacserver_del_process' => '已删除...',

	'apacserver_setpass_login' => '用户名',
	'apacserver_notset_any_redir_site' => '没有重定向到任何网站',
	'apacserver_notset_any_redir_http' => 'HTTP重定向未安装在任何网站上。',
	'apacserver_seluser' => '选择用户',
	'apacserver_http_failedadd' => '参数错误。用户未选中',
	'apacserver_error_pages' => '错误页面',
	'apacserver_list_error_pages' => '您的错误页面',
	'apacserver_error' => '错误',
	'apacserver_code_error' => '错误代码',
	'apacserver_file' => '文件扩展名',
	'apacserver_fild_load' => '下载字段',
	'apacserver_download' => '下载',
	'apacserver_visible_file' => '查看',
	'apacserver_delete' => '删除',
	'apacserver_save' => '保存',
	'apacserver_not_site' => '用户没有网站',
	'apacserver_not_file_download' => '不支持的文件类型',
	'apacserver_error_file_download' => '加载文件时出错',
	'apacserver_optimization' => '网站优化',
	'apacserver_optimization_gzip' => '启用gzip压缩',
	'apacserver_optimization_cesh' => '在浏览器中启用静态缓存',
	'apacserver_successfully' => '保存更改',
	'apacserver_time_cash' => '缓存时间：',
	'apacserver_day' => '天',
	'apacserver_incorecly' => '不是有效的值',
	'apacserver_optimisation_files' => '优化文件',
	'apacserver_bacup_copy' => '备份路径',
	'apacserver_save_bacup_copy' => '保存备份',
	'apacserver_not_files_optimisation' => '找不到优化文件',
	'apacserver_error_directory' => '该目录与正则表达式不匹配',
	'apacserver_action' => '操作',
	'apacserver_action_restore' => '恢复',
	'apacserver_path' => '目录',
	'apacserver_date' => '日期',
	'apacserver_error_id' => '错误ID bacup',
	'apacserver_error_domain' => '域名与正则表达式不匹配',
	'apacserver_error_user' => '用户不匹配正则表达式',
	'apacserver_restore_succesfully' => '从备份中恢复的文件',
	'apacserver_remove_succesfully' => '备份已删除',
	'apacserver_empty_path' => '指定创建备份的路径',
	'apacserver_empty_path_1' => '要创建备份，请指定文件夹',

    'apacserver_wrongdest1' => '目标格式无效。以不带http的格式指定',
	'apacserver_gpagespeed_link_text' => '检查Google PageSpeed Insights',
    'apacserver_extCache' => '缓存扩展：',
    'apacserver_extCacheEx' => '指定通过; ，| |或一个空间。例如：ttf|jpg|jpeg|png|ico|css|bmp|swf|js|txt|tar|zip|pdf|tar.gz|woff2',
    'apacserver_extCacheTimeMin' => '分钟',
    'apacserver_extCacheTimeHour' => '小时',

    'apacserver_cacheHintWrongExt' => '扩展名列表格式错误',
    'apacserver_cacheHintWrongExtExp' => '缓存时间格式错误',
    'apacserver_cacheHintSaveok' => '保存成功',
    'apacserver_cacheWaitPlease' => '请稍等',
    'apacserver_dostatforthisext' => '通过nginx处理这些扩展的静态信息',
    'apacserver_error_reserv_directory' => '错误。 系统保留的目录.',
	'apacserver_error_type_files' => '<br>支持的文件类型 html, htm, php',
	
);