<?php
$lang = array(
    'autoins' => '自动安装程序',
    'cms' => '内容管理系统',
    'selectapptoinstall' => '选择要安装的应用程序',
    'installapp' => '安装',
    'install_app_pleasewait' => '请稍候',
    'install_app_finished' => '已完成',
    'install_app_choose_protocol' => '选择协议',
    'install_app_choose_domain' => '选择域',
    'install_app_choose_domain_desc' => '请选择一个域来安装软件。',
    'install_app_choose_dir' => '指定一个目录',
    'install_app_choose_dir_desc' => '你的域的目录,它不应该存在。即要安装在http://mydomain/dir/只需键入dir。要仅安装在http：//mydomain/将该字段留空。',

    'install_app_sitename' => '网站名称',
    'install_app_sitedesc' => '说明',
    'install_app_importexample' => '导入示例',

    'install_app_adminarea' => '管理员',
    'install_app_adminarea_username' => '登录',
    'install_app_adminarea_pass' => '密码',
    'install_app_adminarea_realname' => '你的名字',
    'install_app_adminarea_email' => '电子邮件',

    'install_app_chooselang' => '选择语言',

    'install_app_plugins' => '选择插件',

    'install_app_wp_loginizer' => '授权尝试的限制（Loginizer）',

    'install_app_forumname' => '论坛名称',

    'install_app_dbhost' => '数据库主机',

    'install_app_installedapp' => '安装的应用程序',
    'install_app_path_install' => '路径',
    'install_app_domain_install' => '域名',
    'install_app_name_install' => '应用程序',
    'install_app_path_delete' => '删除',
    'install_app_path_edit' => '编辑',
    'install_app_option_install' => '选项',
    'install_app_path_ins_failed' => '路径无效',
    'install_app_path_inuse' => '此路径已经存在,检查目录的内容',
    'install_app_install_success' => '成功安装',
    'install_app_install_progress' => '请稍候,正在进行安装。',
    'install_app_delete_success' => '应用程序已删除',
    'install_app_no_installed_app' => '没有安装的应用程序',
    'install_app_client_autoins_stat' => '从客户端激活自动安装程序',
    'autoins_client_stat_complete' => '配置成功保存',
    'autoins_client_stat_message' => '自动安装程序被禁用。请联系您的管理员。',

    'autoins_listautoins' => '应用程序列表',
    'autoins_listautoins_type' => '应用程序类型',
    'autoins_listautoins_name' => '应用程序名称',
    'autoins_listautoins_version' => '版本',
    'autoins_listautoins_option' => '选项',
    'autoins_listautoins_selectapp' => '选择',

    'autoins_listautoins_enable' => '可用',

    'autoins_preg_match_dirins' => '无法安装的目录。请只使用拉丁文,数字和/',
    'autoins_preg_match_sitename' => '请输入网站名称',

    'autoins_preg_match_sitedesc' => '请输入网站说明',
    'autoins_preg_match_login_admin_short' => '登录到站点管理站点的最小长度是6个拉丁字母字符',
    'autoins_preg_match_pass_admin_short' => '站点管理站点的最小密码长度为6个字符',
    'autoins_preg_match_realname' => '输入您的姓名（姓名必须包含至少2个字母,只有拉丁文和西里尔文a-zA-Za-yoyo）',
    'autoins_preg_match_emailadm' => '输入管理员的电子邮件',
    'autoins_preg_match_email' => '输入正确的管理员电子邮件',
    'autoins_saveactiveapp' => '保存',
    'autoins_saveactiveapp_res' => '更新成功',

    'autoins_indirexistfiles' => '文件已经存在于指定的文件夹中。通过覆盖文件来确认安装。',
    'autoins_indirexistfiles_yes' => '是',
    'autoins_indirexistfiles_no' => '否',
    'autoins_install_error' => '错误',
    'autoins_install_wait_user' => '等待用户选择',

    'autoins_deleteapp_inprogress' => '删除正在进行中。请稍等',
    'autoins_cms' => '选择分配',
    'autoins_install' => '选择分配',
    'autoins_error_connect' => '错误连接mysql',
    'autoins_error_not_you' => '这不是你的！',
    'autoins_blog_english' => '英语博客',
    'autoins_blog_no' => '否',
    'autoins_brochure_english' => '小册子英文',
    'autoins_default_english' => '默认英语',
    'autoins_learn_joomla' => '了解Joomla',
    'autoins_test_english' => '测试英语',
    'autoins_ru' => '俄语',
    'autoins_en' => '英文',
    'autoins_clear_cache' => '清除应用程序缓存',
    'autoins_clear_cache_bl' => '缓存正在清理',
    'autoins_clear_cache_ok' => '清除缓存成功',
    'autoins_not_select_cms' => '没有选择CMS',
    'autoins_not_write_cms' => 'CMS写入不正确',
    'autoins_not_version_cms' => '没有CMS版本',
    'autoins_not_vers_incorecly_cms' => 'CMS版本写入不正确',
    'autoins_not_protocol' => '未选择协议',
    'autoins_not_incorecly_protocol' => '协议未正确写入',
    'autoins_not_domain' => '此域名不属于您',
    'autoins_not_dir' => '这个目录很忙。',
    'autoins_susspended' => '成功安装',
    'autoins_not_version_lang' => '语言版本未正确选择',
    'autoins_list_cms' => '已安装的CMS列表',
    'autoins_not_list_cms' => 'CMS列表为空',
    'autoins_list_cmsnot_install' => 'CMS列表',
    'autoins_list_not_arr' => 'CMS数组为空',
    'autoins_list_not_id_arr' => '没有这样的ID来删除CMS',
    'autoins_suspended_dell' => 'CMS成功删除',
    'autoins_error_dell' => 'CMS移除失败',
    'autoins_not_root' => '您没有足够的权利。删除user_edit。',
    'autoins_error_mysql' => '错误mysql查询',
    'autoins_user_cms' => '将CMS安装到用户',
    'autoins_user_config_acc' => '访问',
    'autoins_name_admin' => 'CMS自动安装程序',
    'autoins_please_wait' => '请稍等',
    'autoins_notexist_conf_cmsinputdata' => '没有CMS配置文件inputdata',
    'install_app_adminarea_realname_latin' => '你的名字必须是拉丁字符',
    'autoins_path_admin' => '管理面板的路径',
    'autoins_path_admin_error' => '输入管理面板最小长度为4个字符的路径时出错',
    'autoins_incorrect_ip' => '不是有效的IP地址',
    'autoins_incorrect_forum' => '不是有效的论坛名称',
    'autoins_findcapt' => '搜索',
    'autoins_findcapt_wait' => '执行搜索...',
    'autoins_findcapt_nothingfound' => '找不到',
    'autoins_import_sample' => '导入示例、产品',
    'autoins_domain_not_select' => '未选择或未添加到用户的域名',
    'autoins_userhavenotdomain' => '未添加域名',
    'autoins_data_admin_panel' => '进入管理面板的数据',
    'autoins_brainy' => 'brainy',
    'autoins_login_admin' => '登录管理面板',
    'autoins_redirect_login_admin' => '转到管理面板',
    'autoins_failed_copy' => '无法复制源CMS文件。文件',
    'autoins_failed_user_config' => '不幸的是,远程CMS配置文件不可用',
    'autoins_user_config' => '自定义CMS',
    'autoins_incl_user_config' => '连接用户CMS',
    'autoins_url_user_incl' => 'http://到list.txt的路径',
    'autoins_url_user_add' => '添加',
    'autoins_url' => '网址',
    'autoins_not_include_cms' => '没有连接cms',
    'autoins_error_remote_url' => '错误网址',
    'autoins_error_import_cms' => '导入第三方CMS时出错。检查是否存在远程list.txt',
    'autoins_error_paranetrs' => '参数错误',
    'autoins_cms_error' => 'CMS',
    'autoins_version_error' => '版本',
    'autoins_not_null_cms' => '要连接的cms列表存在',
    'autoins_confirm_remove_cms' => '确认删除连接的cms列表',
    'autoins_yes' => '是',
    'autoins_not' => '否',
    'autoins_error_remove_list_txt' => '删除cms列表时出错',
    'autoins_succp' => '成功',
    'autoins_install_cms' => '通过自动安装程序安装CMS',

);
?>