<?php
$lang = array (
	'blacklist' => 'IP 黑名单',
	'blacklist_ip' => '检查 IP',
	'blacklist_check' => '检查',
	'blacklist_save' => '保存',
	'blacklist_error_domain' => '指定的域名与正则表达式不匹配',
	'blacklist_succesfully' => '成功',
	'blacklist_error_ip' => '输入的IP地址不正确或空白',
	'blacklist_dnsbl_server' => 'dnsbl服务器',
	'blacklist_status' => '状态',
	'blacklist_black' => '在黑名单中',
	'blacklist_ok' => '不在黑名单中',
	'blacklist_detail' => '更多信息',
	'blacklist_list_dnsbl' => 'DNSBL服务器列表',
	'blacklist_check_ip_dnsbl' => '检查黑名单中的IP',
	'blacklist_monitor' => '监控本地IP的时间',
	'blacklist_period_minutes' => '分钟',
	'blacklist_error_minutes' => '分钟值输入不正确',
	'blacklist_many_minutes' => '许多分钟',
	'blacklist_disabled_scan' => '禁用扫描',
	'blacklist_whait_scan' => '正在扫描...',
	'blacklist_whait_save' => '正在保存，请稍等...',
	'blacklist_block_ip' => '阻止IP',
    'blacklist_check_ip_header' => '检查IP',
);
