<?php

$lang = array(
    'certs_control' => 'SSL / TLS管理',
    'service_serv' => '服务',
    'service_domain' => '域名',
    'service_expire' => '期限',
    'service_expire_up' => '过期前过期',
    'service_keysize' => '密钥大小',
    'service_issuer' => '发布者',
    'service_action' => '操作',
    'service_action_loadnewcert' => '下载新的',
    'service_apply_exist' => '申请现有证书',
    'service_install_newcert' => '安装新证书',
    'service_install_newcert_title' => '选择一个或多个服务来安装证书',
    'service_certificate' => '证书',
    'service_privatekey' => '私钥',
    'service_cabunlde' => '证书授权包',
    'service_install_newcert' => '安装',
    'service_reinstall_cert' => '安装新证书',
    'service_install_error_nosel' => '选择您想要安装证书的服务',
    'service_applyexist' => '申请现有证书',
    'service_applyexist_ok' => '成功申请',
    'service_install_new_ok' => '新证书安装成功',
    'service_save' => '保存',
    'service_cancel' => '取消',
    'service_cert_del' => '删除证书',
    'service_overwrite_cert_q' => '要覆盖证书吗？',
    'service_overwrite_cert_yes' => '是',
    'service_overwrite_cert_no' => '不',
    'service_cert_not_ins' => '未安装证书',
    'service_cert_del_confirm' => '执行证书删除',
    'service_cert_del_confirm_yes' => '是',
    'service_cert_del_confirm_no' => '否',
    'service_cert_del_complete' => '删除证书',
    'service_cert_view' => '查看证书',

    'service_cert_install_wrong_cert' => '未安装证书,验证输入证书,密钥和授权包的有效性',


    'tpl_certs_cert' => '证书',
    'tpl_certs_del' => '删除',
    'tpl_certs_certdel' => '删除证书',
    'tpl_certs_cerdeactiv' => '取消激活证书',
    'tpl_certs_key' => '钥匙',
    'tpl_certs_certkey' => '删除密钥',
    'tpl_certs_gen_csr' => '生成CSR',
    'tpl_certs_select_key' => '选择密钥',
    'tpl_certs_key_new' => '新密钥',
    'tpl_certs_domain_name' => '域名',
    'tpl_certs_key_size' => '选择尺寸',

    'tpl_certs_country' => '国家',
    'tpl_certs_state' => '国家',
    'tpl_certs_city' => '城市',
    'tpl_certs_company' => '公司',
    'tpl_certs_division' => '部门',
    'tpl_certs_create_csr' => '创建CSR',
    'tpl_certs_load_crt' => '下载证书',
    'tpl_certs_name' => '名称',
    'tpl_certs_copy_file_crt' => '复制证书文件',
    'tpl_certs_insert_file_crt' => '插入证书文件',
    'tpl_certs_download_crt' => '下载CRT',
    'tpl_certs_your_crt' => '你的CRT',

    'tpl_certs_domain' => '域名',
    'tpl_certs_certs' => '证书',
    'tpl_certs_lenkey' => '密钥长度',
    'tpl_certs_status' => '状态',
    'tpl_certs_func' => '功能',
    'tpl_certs_edit' => '编辑',
    'tpl_certs_save' => '保存',
    'tpl_certs_del_key' => '删除密钥',

    'tpl_certs_c_keys' => '钥匙',
    'tpl_certs_c_crts' => '证书',
    'tpl_certs_c_setting_crts' => '安装证书',
    'tpl_certs_c_list_keycerts' => '域和证书列表',
    'tpl_certs_c_create_priv_key' => '创建私钥',
    'tpl_certs_c_name' => '名称',
    'tpl_certs_c_key_size' => '选择尺寸',
    'tpl_certs_c_create_key' => '创建密钥',
    'tpl_certs_c_download_priv_key' => '下载私钥',
    'tpl_certs_c_copy_key' => '复制密钥',
    'tpl_certs_c_insert_file_key' => '插入密钥文件',
    'tpl_certs_c_load_key' => '下载密钥',
    'tpl_certs_c_your_private_keys' => '你的私人钥匙',

    'tpl_certs_c_generate_csr' => '生成CSR',
    'tpl_certs_c_select_key' => '选择密钥',
    'tpl_certs_c_new' => '新',
    'tpl_certs_c_name_domain' => '域名',
    'tpl_certs_c_select_size' => '选择尺寸',

    'tpl_certs_c_install_cert' => '安装证书',
    'tpl_certs_c_select_domain' => '选择域名',
    'tpl_certs_c_select_crt' => '选择证书',
    'tpl_certs_c_or_load_new' => '或在下面上传',
    'tpl_certs_c_cert1' => '证书（CRT）',
    'tpl_certs_key1' => '私钥（KEY）',
    'tpl_certs_c_list_domain_crts' => '域和证书列表',

    'tpl_certs_s_domain_name' => '域名',
    'tpl_certs_s_ip_addr' => 'IP地址',
    'tpl_certs_s_root_dir' => '根目录',
    'tpl_certs_s_owner' => '所有者',
    'tpl_certs_s_key_size' => '密钥大小',
    'tpl_certs_s_domain_def' => '默认域名',
    'tpl_certs_s_action' => '动作',
    'tpl_certs_s_domain_def_ip' => '将默认域名设置为IP',

    'tpl_certs_s_service_cert' => '服务证书',
    'tpl_certs_s_list_certs' => '证书列表',


    'msg_cert_err_nodomain' => '错误，没有域名',
    'msg_cert_err_nocode' => '错误，国家代码必须包含2个字符，例如RU,UK',
	'msg_cert_err_State'		=> '错误。 州必须以a-z格式填写。.',
    'msg_cert_errCity'		=> '错误。 城市必须以a-z格式填写。.',
    'msg_cert_errCompany'		=> '错误。 公司必须以a-z格式填写.',
    'msg_cert_errOtdel'		=> '错误。 该部门必须以a-z格式完成。.',
	
    'msg_cert_create_info0' => '证书',
    'msg_cert_create_info1' => '已成功创建',
    'msg_cert_err_create_domain' => '错误，加载此域的密钥时出现问题',
    'msg_cert_err_del_cert' => '错误，您的密钥不能被删除,因为它在主机中使用',
    'msg_cert_err_del_cert_cert' => '错误，您的证书无法删除,因为它在主机中使用',
    'msg_cert_ok_del_cert' => '密钥及其证书已被成功删除',
    'msg_cert_ok_del_cert1' => '证书已被删除',
    'msg_cert_err_load_certs' => '错误，证书未加载',
    'msg_cert_let_info0' => '证书',
    'msg_cert_let_info1' => '已配置并应用',

    'msg_cert_ok_unset_dom' => '证书已从域中删除',
    'msg_cert_apply_lets_cert' => '请稍候，有一个创建证书的过程',

    'msg_cert_installed_ok' => '已安装证书',

    'msg_cert_not_installed_yet' => '未安装证书',
    'msg_key_not_installed_yet' => '密钥未安装',
    'msg_cert_install_foremail' => '安装邮件证书',
    'msg_cert_used_foremail' => '用于邮件',

    'msg_cert_generate_cert' => '生成证书',

    'msg_cert_nocertkey' => '没有这样的密钥和证书,不需要删除',

    'certs_control_gen_process' => '生成...',
    'certs_control_apply_cert_process' => '应用...',
    'certs_control_remove_cert_process' => '已删除...',
    'certs_control_install_newcert_process' => '设置...',


    'certs_control_error_validcert' => '错误，密钥与此证书不匹配',
    'certs_control_error_validcert_chain' => '错误，证书授权包不符合此证书',

    'certs_control_failed_gen_letsen' => '生成证书错误，域名必须绑定！',
    'certs_control_failed_gen_letsen_serv' => '生成证书错误，服务器主机名和panel.hostname应该连接到服务器的IP服务器！',


    'certs_control_certload_ok' => '成功下载证书',
    'certs_control_keyload_ok' => '密钥已成功加载',

    'certs_control_certload_failedname' => '未加载证书，证书名称错误',

    'certs_control_certload_wrongformat' => '证书格式无效',
    'certs_control_keyload_wrongformat' => '密钥格式无效',
    'msg_certs_control_certs_info0' => '证书',
    'msg_certs_control_certs_info1' => '成功申请',
    'cert_control_seluser' => '用户名',
    'cert_control_load_wait' => '请稍候',
    'cert_control_gen_lets' => '生成让我们加密',
    'cert_control_gen_lets_renew' => '生成新的允许加密证书',
    'cert_control_letsen_autorenew' => '自动更新证书',
    'cert_control_letsen_autorenew_stat_save' => '保存',
    'certs_control_domain_setdef' => '该域设置为默认IP',
    'certs_control_ipdomain' => 'IP地址',
    'certs_control_gen_letsen_hostname_ok' => '让加密证书成功生成',
    'certs_control_active_autorenew_lets_hostname' => '自动更新证书',
    'certs_control_no_keys' => '无钥匙',
    'certs_control_no_certs' => '没有证书',
    'certs_control_no_domains' => '没有添加域名',
    'certs_control_no_cert' => '删除证书',
    'certs_control_gennew_letsen' => '生成新的允许加密',

    'certs_control_nottimeyet' => '证书',
    'certs_control_nottimeyet2' => '仍然相关',
    'certs_control_pleasereloadpage' => '智能服务证书将在20秒后应用，请重新加载页面以恢复工作',
    'certs_control_pleasereloadpage_del' => '智能服务的证书将在20秒后被删除，请重新加载页面以恢复工作',

    'certs_control_pleasewaitloadinfocert' => '请稍候，正在下载证书信息',
    'certs_control_letsfailedexistgen' => '证书尚未过期,因此您无法为域生成新证书',

    'certs_warn_notinstall_certbot' => '未安装CertBOT，请安装CertBOT',
    'certs_warn_notinstall_certbot_btn' => '安装CertBOT',
    'certs_warn_nothing_sel' => '请选择一个证书',

    'certslets_tip_help' => '要生成Lets Encrypt证书,它将被服务器主机和panel.hostname使用，您可以在<a target=_blank href=/index.php?do=properties>服务器配置</a>部分更改主机名， <br/> <br/>请确保你已经绑定到你的主机名服务器上了',

    'certs_error_nxdomaingencertlets' => '您必须将域绑定到服务器',
    'certs_error_genletssuffauth' => '没有足够的权限来授权域名',
    'certs_error_genletssuffauth_check' => '检查域是否绑定到这个服务器',
    'certs_check_gencertforpanel_host' => '为panel.hostname生成证书',
    'certs_check_gencertforpanel_host_hint' => '要生成证书,请确保面板的域绑定到您的服务器上',
    'certs_select_cert' => '选择证书',
    'certs_data_cert' => '证书数据',
    'certs_too_many_cert' => '稍后生成证书。 证书生成限制已过期.',
    'certs_too_many_cert_services' => '稍后生成服务证书。 证书生成限制已过期.',
    'certs_too_many_error' => '证书创建失败太多。 检查重定向的站点配置，并在几个小时后重试.',

);

?>