<?php

$lang = array(
    'access_denied' => '您没有足够的权限访问此部分',       
    'index' => '主页',
    'input' => '输入',
    'login' => '登录名',
    'logout' => '退出',
    'password' => '密码',
    'ip_manager' => 'IP 管理',
    'ipmanager' => 'IP 管理',
    'login_form' => '登录表单',
    'navigation' => '导航',
    'ip_list' => 'IP列表',
    'send' => '发送',
    'add' => '添加',
    'delete' => '删除',
    'add_time' => '暂时添加',
    'mysql' => 'MySQL',
    'plans' => '计划',
    'plan' => '计划',
    'new_plan' => '新计划',
    'planname' => '资费名称',
    'plan_properties' => '资费属性',
    'host_accounts' => '主机帐户',
    'host_account' => '主机帐户',
    'quota' => '配额',
    'yes' => '是',
    'no' => '否',
    'change' => '更改',
    'install' => '安装',
    'reinstall' => '重新安装',
    'restart' => '重新启动',
    'force_restart' => '强制重启',
    'start' => '运行',
    'stop' => '停止',
    'controls' => '管理',
    'edit' => '编辑',
    'edit_plain' => '编辑为文本',
    'set' => '安装',
    'update' => '更新',
    'version' => '版本',
    'current_version' => '当前版本',
    'add_user' => '添加用户',
    'add_db' => '添加数据库',
    'name' => '名称',
    'add_user_to_db' => '将用户添加到数据库',
    'user' => '用户',
    'db' => '数据库',
    'exist_users' => '现有用户',
    'exist_dbs' => '现有数据库',
    'privileges' => '权限',
    'data' => '数据',
    'structure' => '结构',
    'default_mycnf' => '恢复默认my.cnf',
    'change_root_pass' => '更改密码root',
    'server_control' => '服务器管理',
    'complectation' => '包装内容',
    'php_install' => '安装php',
    'apache_install' => '安装apache',
    'apache_control' => '管理apache',
    'change_passwords' => '更改密码',
    'nginx_install' => '安装nginx',
    'autostatic' => '代理静态',
    'nginx_control' => '管理nginx',
    'server_install' => '服务器安装',
    'server_complectation' => '服务器包',
    'edit_apacheconf' => '编辑apache配置',
    'edit_nginxconf' => '编辑nginx配置',
    'add_site' => '添加网站',
    'site' => '网站',
    'site_name' => '网站名称',
    'site_alias' => '网站别名',
    'site_admin' => '网站管理员',
    'site_root' => '网站根文件夹',
    'default_conf' => '恢复默认配置',
    'email' => '电子邮件',
    'ip' => 'IP',
    'domain' => '域名',
    'aliases' => '别名',
    'dir' => '目录',
    'reload_hosts' => '重新组装虚拟主机',
    'remove_host' => '删除虚拟主机',
    'current_complectation' => '当前配置',
    'basedir' => '基本目录',
    'enter' => '进入',
    'options' => '选项',
    'please_wait' => '请稍等',
    'processing' => '进程正在进行中。请稍等',
    'processing' => '删除中...',
    'access_error' => '访问错误',

    'topinfo_count_sites' => '网站',
    'topinfo_ftp' => 'FTP帐户',
    'topinfo_bandwidth' => '流量',
    'topinfo_databases' => '数据库',
    'topinfo_emailboxes' => '邮箱',
    'topinfo_mailperhour' => '每小时的信件数量',
    'topinfo_plan' => '计划',
    'topinfo_disk' => '磁盘',
    'topinfo_ip' => 'IP',
    'topinfo_shell_access' => 'Shell',
    'topinfo_language' => '语言',
    'topinfo_username' => '登录',
    'topinfo_rootdir' => '主文件夹',
    'topinfo_group' => '群组',
    'topinfo_clamav' => 'Clamav',
    'topinfo_exim' => 'Exim',
    'topinfo_dovecot' => 'Dovecot',
    'topinfo_postfix' => 'Postfix',
    'topinfo_webserver' => 'webserver',
    'topinfo_cron' => 'cron',
    'topinfo_db' => 'db',
    'topinfo_named' => '命名',
    'topinfo_loadavg' => 'Load_AVG',
    'topinfo_diskspace' => '磁盘',
    'topinfo_proftpd' => 'FTP',
    'topinfo_pureftpd' => 'FTP',
    'topinfo_brainy' => 'brainy',
    'topinfo_opendkim' => 'OpenDKIM',
    'topinfo_brainysqld' => 'Brainy SQL',
    'topinfo_postgresql' => 'PostgreSQL',

    'topinfo_g_nginx' => 'Nginx',

    'topinfo_csf' => 'CSF',
    'topinfo_spamassassin' => 'SpamAssassin',

    'topinfo_saveok' => '保存成功',
    'common_seluserplease' => '选择用户',
    'common_user_notselect' => '未选择用户',
    'nothing_found' => '找不到',
    'search_is_runnig' => '正在搜索中',
    'common_notselect' => '未选择',
    'common_putname_label' => '输入名称',
    'common_user_current' => '当前用户',
    'common_value_unlim' => '无限制',
    'main_title' => 'BrainyCP - 服务器控制面板',
    'post_title' => ' - BrainyCP',

    'min' => 'min',

    'topinfo_tip' => '数据在后台更新',
    'topinfo_tip_one' => '所有人',
    'topinfo_tip_not_one' => '每个',

    'common_killall_ok' => '进程被强制停止',

    'upload_caption' => '文件未被选中',
    'upload_btn_text' => '选择文件',

    'common_pagegencountonpage' => '每页数量：',

    'navigate_header_list' => '按类别分类',
    'navigate_header_tile' => '所有栏目',

    'context_menu_password' => '将密码设置为目录',
    'context_menu_optimization' => '加快网站速度',
    'context_menu_www' => '启用重定向',
    'context_menu_certs_control' => '安装SSL证书',
    'context_menu_certs_control_lets' => '安装让加密证书',
    'context_menu_http' => '配置HTTPS重定向',
    'context_menu_server_control_1' => '编辑PHP指令',
    'context_menu_openfolder' => '管理文件管理器中的文件',
    'context_menu_antivirus' => '检查网站是否有杀毒软件',
    'context_menu_logging' => '记录',
    'context_menu_web_statistics' => '统计信息',
    'context_menu_webserver_config' => '设置虚拟主机',
    'context_menu_mailforward' => '配置邮件转发',
    'context_menu_spf' => '管理SPF',
    'context_menu_opendkim' => '管理DKIM',
    'context_menu_mail_antivirus' => '使用防病毒扫描邮件文件夹',
    'context_menu_mail_statistic' => '邮政统计',
    'context_menu_mail_filter' => '添加过滤器',
    'auth_title' => 'BrainyCP - 授权页面',

    'common_config_monitor' => '配置',
    'common_config_updatecaption' => '更新：',
    "common_inhour" => "in",
    "common_every1hour" => "所有人",
    "common_every2to24" => "所有人",
    "common_hour1hour" => "小时",
    "common_hour2to4" => "小时",
    "common_hour5to24" => "小时",

    "common_every1minute" => "每个",
    "common_every2to60" => "每个",
    "common_minute1hour" => "分钟",
    "common_minute2to4" => "分钟",
    "common_minute5to60and0" => "分钟",
    "common_everyhoursend" => "每小时",

    "gen_pass" => "生成密码",
    "difficult_pass" => "复杂性",

    "common_demo_version" => "面板处于演示模式,文件管理器处于只读模式。",
    'common_demo_message' => '对不起,此操作已在演示版本中停用。',

    "choose_file" => "选择文件",
    "no_file" => "没有选择文件",

    "child_human_log_mysqldb" => "创建数据库的备份副本",
    "child_human_log_preparelog1" => "准备用户文件",
    "child_human_log_preparelog2" => "复制文件。",
    "child_human_log_preparelog3" => "创建所需的目录。",
    "child_human_log_process" => "",
    "child_human_log_data_backup" => "写入备份信息",
    "child_human_log_remove_temp" => "删除临时文件",
    "child_human_log_finish_oper" => "完成操作",
    "child_human_log_finish_emailsendcomplete" => "如果安装发送电子邮件。",
    "child_human_log_finish_calcbackupsfordelete" => "计算备份副本的数量",
    "child_human_log_finish_completecreatebackup" => "备份已成功完成。",
    "child_human_log_startcreate_backup" => "启动备份创建用户",
    "child_human_log_uptodrop" => "将备份下载到Dropbox。",
    "child_human_log_uptogdrive" => "在GoogleDrive上下载备份",
    "child_human_log_yadisk_putfile" => "将备份下载到YandexDisk。",
    "child_human_log_ftp" => "将备份下载到FTP。",

    "child_human_log_uptodrop_rest" => "从Dropbox下载备份",
    "child_human_log_uptogdrive_rest" => "从GoogleDrive下载备份",
    "child_human_log_yadisk_putfile_rest" => "从YandexDisk下载备份",
    "child_human_log_ftp_rest" => "从FTP下载备份",


    "child_human_logtrans_start" => "开始账户转账",
    "child_human_logtrans_transuser" => "用户转移",
    "child_human_logtrans_transuserend" => "用户迁移已完成",
    "child_human_logtrans_restoreuser" => "用户恢复。",
    "child_human_logtrans_restoredbuser" => "恢复用户数据库的用户",
    "child_human_logtrans_restoredbuserdbs" => "恢复用户数据库",
    "child_human_logtrans_autoins_backup" => "还原已安装的CMS用户列表",
    "child_human_logtrans_restore_backups_jobs" => "恢复用户的备份作业列表。",

    "child_human_logtrans_restore_restoreftpacc" => "恢复FTP用户帐户",
    "child_human_logtrans_restore_restorevhosts" => "还原虚拟用户主机",
    "child_human_logtrans_restore_change_ips_domains" => "更改用户虚拟主机的IP地址",
    "child_human_logtrans_restore_vhostsrebuild" => "重建虚拟用户主机",
    "child_human_logtrans_restore_addzones" => "添加DNS区域给用户",
    "child_human_logtrans_restore_restore_emails_user" => "还原电子邮件帐户",
    "child_human_logtrans_restore_email_forward" => "恢复电子邮件重定向",
    "child_human_logtrans_restore_dns_user" => "恢复所需的文件",
    "child_human_logtrans_restore_dkimkeys_user" => "恢复DKIM密钥",
    "child_human_logtrans_restore_webserver_includes_user" => "恢复虚拟主机的设置",
    "child_human_logtrans_restore_passdir_user" => "恢复用户设置",
    "child_human_logtrans_restore_httpredir_user" => "恢复HTTP重定向",
    "child_human_logtrans_restore_siteredir_user" => "恢复网站重定向",
    "child_human_logtrans_restore_opti_user" => "恢复网站优化设置",
    "child_human_logtrans_crontab" => "恢复用户作业的CRON",

    "child_human_logtrans_restorebackuphint" => "用户恢复已启动",
    "child_human_logtrans_restorebackuphintend" => "用户恢复已完成",
    "child_human_logtrans_clearuserdata" => "在恢复之前删除当前用户",
    "child_human_logtrans_restore_passdir_user" => "恢复用户设置",

    "child_human_logtrans_userexist" => "具有此名称的用户已存在",

    "child_human_dns_type_cluster" => "同步类型：群集",
    "child_human_dns_type_server" => "同步类型：服务器",
    "child_human_dns_ipaddress" => "同步IP地址：",
    "child_human_dns_typeserver" => "服务器类型：",
	"child_human_backup_prepare" => "运行查询...",

    "common_wrongname_pass" => "登录或密码不正确",

    "child_human_backup_control_sum" => "计算备份校验和",
    "child_human_backup_logtrans" => "日志：",
    "child_human_backup_logtrans_ok" => "备份已成功保存",

    "common_autoloadservice_after_reset_server" => "服务器重启后服务启动",
    "common_autoloadservice_title" => "启动",

    "child_human_hostaccsetjailhost" => "恢复用户环境的监狱设置",
    "child_human_hostaccsetjailphp" => "恢复jail php用户设置",
	"child_human_backup_opensslcrypt" => "加密/дешифрование бэкапа",
    "child_human_backup_openssldecryptFailed" => "解密失败了",

    "child_human_hostaccJaillOffBeforeRestore" => "用户恢复.",
    "child_human_hostaccRestoreContinue" => "复制文件.",
	
    "current_lang" => "俄语",

    "child_human_listDBuserrestore" => "数据库恢复列表：",

    'common_showAllData' => '全部显示',
    'common_server_resource_limit' => '限制服务器资源',
    'common_access_is_denied' => '拒绝访问',

	
    "child_human_logtransStart" => "请等待迁移",

    "child_human_logtransStartFromRemote" => "请等待，从远程服务器转移用户",

    'child_human__yandexGetBackup' => '从YandexDisk获取备份',





);
?>