<?php

$lang = array(
    'crontab'           => '配置cron',
    'clear_script'           => '清理脚本',
    'cron_ownvalue'           => '...',
    'cron_mon'           => '星期一',
    'cron_tue'           => '星期二',
    'cron_wed'           => '星期三',
    'cron_thu'           => '星期四',
    'cron_fri'           => '星期五',
    'cron_sat'           => '星期六',
    'cron_sun'           => '星期日',
    'cron_*_short'           => '*',
    'cron_mon_short'           => '星期一',
    'cron_tue_short'           => '星期二',
    'cron_wed_short'           => '星期三',
    'cron_thu_short'           => '星期四',
    'cron_fri_short'           => '星期五',
    'cron_sat_short'           => '星期六',
    'cron_sun_short'           => '星期日',
    'cron_min_fail_format'           => 'cron分钟格式无效',
    'cron_hours_fail_format'           => 'cron时钟格式无效',
    'cron_days_fail_format'           => 'cron日期格式无效',
    "cron_suspended_acc"=>"添加、编辑、删除Cron作业被阻止，请联系您的管理员。",
	
    'cron_install'           => '已安装',
    'cron_noinstall'           => '未安装',
    'cron_add_comand'           => '添加命令',
    'cron_delete'           => '删除',
    'cron_delete_process'           => '已删除...',
    'cron_edit'           => '编辑',
    'cron_save'           => '保存',
    'cron_cansel'           => '取消',
    'cron_service'           => 'cron服务',
    'cron_status'           => 'cron服务状态',
    'cron_install_cr'           => '安装cron',
    'cron_delete_cr'           => '删除cron',
    'cron_reinstall_cr'           => '重新安装cron',
    'cron_detail'           => '更多信息',
    'cron_hide'           => '隐藏',
    'cron_control'           => '控制cron',
    'cron_start'           => '开始',
    'cron_stop'           => '停止',
    'cron_reboot'           => '重新启动',
    'cron_task'           => 'cron任务',
    'cron_select_user'           => '选择用户',
    'cron_nocheck'           => '未选择',
    'cron_add'           => '保存电子邮件',
    'cron_changes'           => '更改成功',
    'cron_null'           => '不正确的电子邮件格式',
    'cron_minute'           => '分',
    'cron_hour'           => '小时',
    'cron_day'           => '日',
    'cron_month'           => '月',
    'cron_week'           => '周',
    'cron_comand'           => '命令',
    'cron_user_email'           => '电子邮件（用于发送通知）：',
    'cron_save_ok'           => '数据成功修改',

    'cron_command_err'           => '命令字段错误',
    'cron_day_err'           => '没有正确指定星期几',
    'cron_month_err'           => '没有正确指定月份',
    'cron_username_err'           => '用户名无效',
    'cron_params_err'           => '参数错误',
    'cron_start_ok'           => '启动',
    'cron_stop_ok'           => '停止',
    'cron_start_failed'           => '运行时出错',
    'cron_inprogress_oper'           => '请稍候',
    'cron_inprogress_oper_finish'           => '操作完成',
    'cron_notins_ok'           => '未安装',
    'cron_ins_ok'           => '已安装',
    'cron_no_tasks'           => '没有任务',
    'cron_job_add_ok'           => '成功添加任务',
    'cron_demo_mess'           => '在演示模式下，所有更改都只有一个可视角色，实际上，cron任务不会被编辑、创建或删除。',

    'cron_testrunjob'           => '运行',
    'cron_hintAddJob'          => '要添加的命令示例：<br/>1. /usr/bin/phpXX/bin/php /home/user/script.php，其中XX是php的版本<br/><br/>2. 隐藏脚本消息的输出<br/> /usr/bin/phpXX/bin/php -q /home/user/script.php >/dev/null 2>/dev/null<br/><br/> 3. /usr/bin/wget -t 1 -O - `http://site.com/script.php?p1=a&p2=b`',
    'cron_hintAddJobPHPAllow' => '可用的PHP版本： ',
    'cron_comand_sucessf' => '命令完成.<br>',
	
);

?>

