<?php

$lang = array(
    'ftp'		=> 'FTP',
    'start'		=> '运行',
    'stop'		=> '停止',
    'default_vsftpd'		=> '恢复默认的vsftpd.conf',
    'default_pureftpd'		=> '恢复标准的pure-ftpd.conf',
    'default_proftpd'		=> '恢复默认的proftpd.conf',
    'homedir_user'		=> '用户主目录',
    'delete_homedir_user'		=> '删除用户的根目录',
    'ftp_path'		=> '主目录',
    'ftp_quota_use'		=> '使用',
    'ftp_quota_avail'		=> '可用',
    'ftp_change_pass'		=> '更改密码',
    'ftp_change_pass_placeholder'		=> '输入新密码',
    'ftp_change_quota'		=> '更改配额',
    'ftp_change_quota_placeholder'		=> '输入配额大小',
    'ftp_change_currennt_quota'		=> '当前配额',
    'ftp_action'		=> '操作',
    'ftp_error_add_user_exist'		=> '使用这个名字的用户已存在',
    'ftp_success_add_user'		=> '用户添加',
    'ftp_deleted'		=> '已删除',
    'ftp_installed'		=> '已安装',
    'ftp_reinstalled'		=> '重置',
    'ftp_install'		=> '安装',
    'ftp_reinstall'		=> '重新安装',
    'ftp_delete'		=> '删除',
    'ftp_start'		=> '运行',
    'ftp_stop'		=> '停止',
    'ftp_restart'		=> '重新启动',
    'ftp_stat'		=> '状态',
    'ftp_server'		=> 'FTP服务器',
    'ftp_stat_started'		=> '启动',
    'ftp_stat_started_failed'		=> '运行错误',
    'ftp_stat_stopped'		=> '停止',
    'ftp_stat_restarted'		=> '成功重新启动',
    'ftp_process_launched'		=> '正在运行，请稍候......',
    'ftp_process_finished'		=> '操作完成。',
    'ftp_configure_share'		=> '配置',
    'ftp_conf_edit'		=> '编辑设置',
    'ftp_conf_save'		=> '保存',
    'ftp_conf_save_file'		=> '保存文件',
    'ftp_conf_save_success'		=> '保存成功',
    'ftp_restore_default_settings'		=> '恢复默认设置',
    'ftp_restore_default_settings_success'		=> '恢复标准设置',
    'ftp_repairmyconf'		=> '恢复我的设置',
    'ftp_repairmyconf_success'		=> '已恢复我的设置',

    'ftp_login'		=> '用户名',
    'ftp_path'		=> '主文件夹',
    'ftp_usage'		=> '使用',
    'ftp_quota'		=> '配额',
    'ftp_action'		=> '操作',
    'ftp_search_user'		=> '查找',
    'ftp_accounts'		=> 'FTP帐户',
    'ftp_search_user_holder'		=> '输入登录名',
    'ftp_pagesize'		=> '每页帐户数',

    'ftp_useradd'		=> '添加用户FTP',
    'ftp_pass_new'		=> '密码',
    'ftp_homedir'		=> '主文件夹',
    'ftp_newuser_add'		=> '添加FTP帐户',
    'ftp_newuser_add_success'		=> '用户添加',
    'ftp_edit_user_sub'		=> '编辑用户',
    'ftp_delete_user_sub'		=> '删除',
    'ftp_edit_user_quota'		=> '编辑配额',
    'ftp_edit_user_pass'		=> '更改密码',
    'ftp_edit_user_quota_title'		=> 'FTP配额',
    'ftp_edit_user_quota_mb'		=> 'MB',
    'ftp_edit_user_quota_cancel'		=> '取消',
    'ftp_edit_user_quota_file'		=> '编辑文件配额',

    'ftp_edit_pass_enter'		=> '密码',
    'ftp_edit_pass_enter_again'		=> '重新输入密码',
    'ftp_edit_pass_strength_pass'		=> '密码强度',
    'ftp_edit_cancel'		=> '取消',
    'ftp_del_user'		=> '删除用户',
    'ftp_del_homedir'		=> '删除用户的主文件夹',
    'ftp_del_user_cancel'		=> '取消',
    'ftp_del_user_confirm'		=> '删除',
    'ftp_del_user_process'		=> '删除...',
    'ftp_config_ftp_client'		=> '配置FTP客户端',
    
    'ftp_count_accept'		=> '应用',
    'ftp_user_exist'		=> '用户已经存在',
    'ftp_import_ok'		=> '导入成功',
    'ftp_import_failed'		=> '导入时发生错误',

    'ftp_selectftpacc'		=> '选择用户',

    'ftp_searchftpacc'		=> '输入用户名',

    'ftp_addaftpsubacc'		=> '添加FTP子帐户',

    'ftp_noftpins'		=> 'FTP服务器未安装，请联系管理员',

    'ftp_user_login_new_wrong'		=> '无效的用户登录格式',
    'ftp_user_login_new_wrong_null'		=> '输入用户名',
    'ftp_user_login_pass_null'		=> '输入密码',
    'ftp_user_userdir_null'		=> '输入主文件夹',
    'ftp_user_userdir_wrong'		=> '主文件夹格式无效',

    'ftp_user_quota_null'		=> '输入配额大小',
    'ftp_user_quota_wrong'		=> '配额格式无效，必须是整数',

    'ftp_user_add_ok'		=> '用户成功添加',

    'ftp_generatelog_userfolder'		=> '生成日志',
    'ftp_generatelog_ok'		=> '日志成功生成',
    'ftp_cron_run_failed'		=> '警告：cron未在服务器上运行，模块可能无法正常工作安装并运行crond以进行正确操作。',

    'ftp_suspended_acc'		=> '添加，编辑，删除FTP帐户被阻止，请联系您的管理员。',
    'ftp_setting'		=> '配置FTP服务器',
    'ftp_not_instaled'		=> '未安装',
    'ftp_p_f'		=> '纯粹ftpd',
    'ftp_proftpd'		=> 'proftpd',
    'ftp_det'		=> '更多信息',
    'ftp_hide'		=> '隐藏',
    'ftp_ns'		=> '未选中',
    'ftp_f_e'		=> '对于行家',
    'ftp_f_l'		=> '对于用户',//对于lilok
    'ftp_y'		=> '是',
    'ftp_n'		=> '否',
    'ftp_on'		=> '开',
    'ftp_off'		=> '关',

    'ftp_pass_change_ok'		=> '密码更改成功',
    'ftp_quota_change_ok'		=> '配额成功更改',

    'ftp_adduser_failed_overlimit'		=> '已超过FTP帐户限制，FTP帐户的最大数量',

    'ftp_nousersadded'		=> '用户未创建',
    'ftp_noaccounts'		=> '没有帐户',
    'ftp_not_passwd_for_passwd'		=> '密码不匹配',
    'ftp_main_ftpacc'		=> '主要的FTP帐户无法删除',
    'ftp_quota_not_use'		=> '配额未使用',
    'ftp_quota_hint'		=> '无限制的配额请输入0',
    'ftp_user_readonly'		=> '只读',
    'ftp_user_readonly_res_ok_save'		=> '访问ftp帐户已成功更改',
);

?>