<?php
$lang = array(
    "hashmon" => "控制hash总和",
    "hashmon_path" => "监控目录",
    "hashmon_addnewmon" => "编辑监控任务",
    "hashmon_addnewmonbtn" => "添加",
    "hashmon_period_run" => "启动期",
    "hashmon_period_run_day" => "每日",
    "hashmon_period_run_week" => "每周",
    "hashmon_period_run_month" => "每月",
    "hashmon_period_run_time" => "启动时间",
    "hashmon_period_run_time_hh" => "hh",
    "hashmon_period_run_time_mm" => "mm",
    "hashmon_period_run_time_weeksel" => "选择每周运行的日子",
    "hashmon_period_run_time_weeksel_mon" => "星期一",
    "hashmon_period_run_time_weeksel_tue" => "星期二",
    "hashmon_period_run_time_weeksel_wed" => "星期三",
    "hashmon_period_run_time_weeksel_tue" => "星期四",
    "hashmon_period_run_time_weeksel_fri" => "星期五",
    "hashmon_period_run_time_weeksel_sat" => "星期六",
    "hashmon_period_run_time_weeksel_sun" => "星期日",
    "hashmon_period_run_time_datesel" => "指定要运行的日期",
    "hashmon_period_run_time_datesel_del" => "删除",
    "hashmon_period_run_time_datesel_add" => "添加开始日期",
    "hashmon_period_run_time_sendemailafterscan" => "完成后发送电子邮件",
    "hashmon_period_run_time_status" => "状态",
    "hashmon_run_includeonly" => "仅搜索",
    "hashmon_run_includeonly_placeholder" => "通过,;或空格指定文件扩展名,例如：php,txt; sh py 指定目录：dir:/home/folder",
    "Hashmon_run_includeonly_placeholder_full" => "通过指定文件扩展名 , ; 或一个空间。<br/>例如： php,txt; sh py.<br/>指定目录： dir:/home/文件夹 <br/>指定搜索所选扩展名的目录： dir:/文件夹/||txt||php<br/>可以写入多行",
    "hashmon_run_exclude" => "排除文件",
    "hashmon_run_exclude_placeholder" => "通过;;或空格指定文件扩展名,例如：php,txt; sh py。",

    "hashmon_createhash" => "创建快照",
    "hashmon_hashlist_path" => "路径",
    "hashmon_hashlist_date" => "创建时间",
    "hashmon_hashlist_mainhash" => "主要",
    "hashmon_hashlist_option" => "选项",
    "hashmon_hashlist_delete" => "删除",
    "hashmon_hashlist_select" => "选择用于比较",

    "hashmon_wrongdir" => "指定的目录无效",
    "hashmon_pleasewait" => "请稍候",
    "hashmon_nofindbymask" => "没有找到指定监视过滤器的文件",
    "hashmon_findbymask" => "快照已创建",
    "hashmon_pathnotexist" => "指定的目录不存在",
    "hashmon_option_removehash" => "删除快照",
    "hashmon_option_setmain" => "将快照分配给主人",
    "hashmon_option_viewhash" => "查看快照",
    "hashmon_option_denydeletehash" => "你不是这张照片的拥有者",
    "hashmon_option_comparehash" => "比较",
    "hashmon_option_uncheck" => "删除选择",
    "hashmon_option_complete_compare" => "比较成功",
    "hashmon_hashlist_no" => "尚未创建图片",
    "hashmon_hashlist_table_title" => "快照列表",
    "hashmon_comphash_table_title" => "运行图像比较处理列表",
    "hashmon_comphash_table_title_noproc" => "没有正在运行的进程",
    "hashmon_comphash_table_title_captch1" => "快照1",
    "hashmon_comphash_table_title_captch2" => "快照2",
    "hashmon_comphash_table_title_captch_createtime" => "创建时间",
    "hashmon_comphash_table_title_comp_starttime" => "启动时间",
    "hashmon_comphash_table_title_comp_completeperc" => "完成：",

    "hashmon_comphash_table_title_finish" => "完成图片比较的列表",
    "hashmon_stop_comp" => "停止",

    "hashmon_comphash_table_compared_no" => "没有拍摄图像的比较",
    "hashmon_comphash_table_compared_view" => "查看结果",
    "hashmon_comphash_table_compared_manage" => "管理",
    "hashmon_comphash_table_compared_remove_rescomp" => "删除",
    "hashmon_comphash_table_compared_view_rescomp" => "查看",
    "hashmon_comphash_table_compared_del_deny" => "无权删除结果",
    "hashmon_comphash_table_compared_view_deny" => "没有查看结果的权限",

    "hashmon_comphash_table_compared_view_title" => "查看图片比较结果",
    "hashmon_comphash_table_compared_view_newin" => "新文件：",
    "hashmon_comphash_table_compared_view_remove" => "删除的文件：",
    "hashmon_comphash_table_compared_view_newin_not" => "未检测到",
    "hashmon_comphash_table_compared_view_diff" => "快照之间的文件差异：",
    "hashmon_comphash_table_compared_view_diff_no" => "找不到文件",
    "hashmon_comphash_seldomain" => "选择域",
    "hashmon_comphash_nodomainuser" => "没有域名",

    "hashmon_add2cronjobs" => "添加任务",
    "hashmon_updatecronjobs" => "更新",
    "hashmon_removecronjobs" => "取消",
    "hashmon_namejob" => "任务名称",
    "hashmon_namejob_exist" => "具有指定名称的任务已经存在。创建另一个。",
    "hashmon_namejob_exist_noedit" => "具有指定名称的任务不存在。",
    "hashmon_namejob_empty" => "任务名称不能为空。",
    "hashmon_wrongdir_format" => "扫描的目录格式无效",
    "hashmon_wrong_namejob" => "目标名称格式无效",
    "hashmon_wrong_findonlywith" => "该字段的格式无效仅使用扩展名搜索",
    "hashmon_wrong_findonlywithout" => "用扩展名,文件夹排除文件的格式无效",
    "hashmon_wrong_period" => "无效期格式",
    "hashmon_wrong_timehourmin" => "错误的启动时间格式",
    "hashmon_wrong_weekdays" => "错误格式星期几",
    "hashmon_wrong_numbermonth" => "开始日期格式无效",
    "hashmon_job_save_complete" => "成功保存",
    "hashmon_job_list" => "监控任务列表",

    "hashmon_job_listtable_title_name" => "名称",
    "hashmon_job_listtable_title_stat" => "状态",
    "hashmon_job_listtable_title_timerun" => "启动时间",
    "hashmon_job_listtable_title_opt" => "选项",

    "hashmon_job_listtable_title_nojobsadd" => "未添加监控任务",
    "hashmon_job_notifyemail" => "电子邮件通知",
    "hashmon_job_notifyemail_hint" => "监控任务完​​成后,会发送一条消息给指定的电子邮件,统计信息包括已更改,删除和添加的文件",
    "hashmon_job_notifyemail_format" => "输入电子邮件通过;或空间",
    "hashmon_job_selmaincapt" => "选择一个基本镜头",
    "Hashmon_job_selmaincapt_hint” =>“与选定的图像将被做了一个比较新的,删除或修改文件的发现。<BR/>如果你没有一个图片,请创建它首先将监控的任务之前",
    "hashmon_delcapt_comp_succ" => "图片比较已删除",
    "hashmon_emaillistnotify_wrong" => "电子邮件格式无效",
    "hashmon_notexistmaincapt" => "选定的主快照不存在",
    "hashmon_job_status" => "活动",
    
    'hashmon_period_intime' => '在',
    'hashmon_period_ondays' => '按数字',
    'hashmon_period_day' => '每日',
    'hashmon_period_week' => '每周',
    'hashmon_period_month' => '每月',
    'hashmon_weekly_short_arr'=> array('星期一','星期二','星期三','星期四','星期五','星期六','星期日'),
    'hashmon_job_runnow' => '运行',
    'hashmon_job_edit' => '编辑',
    'hashmon_job_remove' => '删除',
    'hashmon_tablejob_title_maincapt' => '基本快照',
    'hashmon_tablejob_removedeny' => '您无权删除此监控任务',
    'hashmon_tablejob_removeok' => '删除任务',
    'hashmon_email_erorr_send' => '使用监测统计信息发送消息时出错',
    'hashmon_email_res_monit' => '监视目录的结果',
    'hashmon_hash_removerow_selected' => '已删除选中',
    'hashmon_denyusespecsymbol' => '您不能在任务名称中使用_和空格',
    'hashmon_oraddjob' => '或',
    'hashmon_oraddjob_btn' => '添加任务',
    'hashmon_firstcreatehash' => '没有快照，请先创建一个快照',
    'hashmon_selallcheck' => '全选',
    
    

);

?>