<?php

$lang = array(
    'hostacc' => '主机帐户',
    'hostacc_suspended_sites_ok' => '主机帐户上的网站被阻止。',
    'hostacc_unsuspended_sites_ok' => '主机帐户上的网站已解锁。',
    'hostacc_suspended_ftp_ok​​' => '主机帐户上的FTP被禁用',
    'hostacc_unsuspended_ftp_ok​​' => '主机帐户上的FTP被解锁。',
    'hostacc_suspended_email_ok' => '主机帐户上的邮件被锁定。',
    'hostacc_unsuspended_email_ok' => '主机帐户上的邮件被解锁。',
    'hostacc_suspended_cron_ok' => '主机帐户禁用Cron',
    'hostacc_unsuspended_cron_ok' => '主机帐户上的Cron被解锁。',
    'hostacc_suspended_pa​​nel_ok' => '用户被拒绝访问面板。',
    'hostacc_unsuspended_pa​​nel_ok' => '访问面板解锁。',
    'hostacc_suspended_shell_ok' => '对用户的外Shell访问被阻止。',
    'hostacc_unsuspended_shell_ok' => '外Shell访问被解锁。',
    'hostacc_suspended_full_ok' => '用户的访问被完全阻止。',
    'hostacc_unsuspended_full_ok' => '用户的访问被完全解锁。',
    'hostacc_unsuspended_user_del' => '您无权删除此用户。',
    'hostacc_unsuspended_user_del_ok' => '用户已成功删除。',


    'hostacc_stat_susp_sites_title' => '封锁网站',
    'hostacc_stat_susp_ftp_title' => '阻止FTP',
    'hostacc_stat_susp_email_title' => '阻止邮件',
    'hostacc_stat_susp_cron_title' => 'cron',
    'hostacc_stat_susp_shell_title' => 'shell',
    'hostacc_stat_susp_panel_title' => '面板锁定',
    'hostacc_stat_susp' => '是',
    'hostacc_stat_unsusp' => '否',
    'hostacc_stat_susp_reason' => '阻止原因',
    'hostacc_stat_unsusp_ftpuser_failed' => 'FTP用户解锁出错',

    'hostacc_stat_confirm_susp' => '确认锁定',
    'hostacc_btn_susp' => '阻止',
    'hostacc_btn_unsusp' => '解锁',

    'hostacc_btn_susp_full' => '全部阻止',
    'hostacc_btn_unsusp_full' => '完全解锁',
    'hostacc_date_susp' => '上次锁定日期',
    'hostacc_date_unsusp' => '最后解锁日期',

    'Hostacc_delete_ip_from_acc_failed' => '这些IP：<br/>{ips} <br/>使用：<BR/>{domains}<br/>要在上述指定域的配置中更改IP，请选择其中一个可用IP：<br/>',
    'hostacc_data_unset_plan' => '未指定',
    'hostacc_data_unset_group' => '未指定',

    'lang_rootaccess' => '访问ROOT',
    'lang_ftp_access_restart' => 'FTP重新启动',
    'lang_ftp_access_install' => '重新安装FTP',
    'lang_is_reseller' => '调解员',
    'lang_is_reseller_planview' => '查看中间人计划',
    'lang_is_reseller_groupview' => '查看中介组',
    'lang_is_reseller_groupcreate' => '为中介创建一个群组',
    'lang_is_reseller_plancreate' => '与中介人建立计划',

    'msg_unlimited0'				=> '无限',
    'msg_unlimited'				=> '&#8734',
    'msg_no_permission_suspend_sites' => '无法停止网站！',
    'msg_no_permission_unsuspend_sites' => '无权运行网站！',
    'msg_no_permission_suspend_ftp' => '无法停止FTP！',
    'msg_no_permission_unsuspend_ftp' => '没有权限启动FTP！',
    'msg_no_permission_suspend_shell' => '没有权限停止shell！',
    'msg_no_permission_unsuspend_shell' => '没有权限启动shell！',
    'msg_no_permission_suspend_cron' => '没有权限停止CRON！',
    'msg_no_permission_unsuspend_cron' => '没有权限运行CRON！',
    'msg_no_permission_suspend_panel' => '没有权限停止面板！',
    'msg_no_permission_unsuspend_panel' => '没有权限启动面板！',
    'msg_no_permission_suspend_full' => '没有权限完全停止工作！',
    'msg_no_permission_unsuspend_full' => '无权执行完全重启！',

    'msg_no_permission_edit' => '你没有权限编辑这个。',
    'msg_no_group_name' => '没有组名',
    'msg_no_group_add_ok' => '该群组已成功添加',
    'msg_no_group_edit_ok' => '该群组已成功编辑',
    'msg_seccess_del' => '成功删除',
    'msg_add_host_acct' => '添加主机帐户',
    'msg_edit_host_acct' => '编辑主机帐户',
    'msg_save_host_acct' => '保存主机帐户',
    'msg_add_plan' => '添加费率',
    'msg_edit_plan' => '编辑关税',
    'msg_edit_user' => '编辑用户',
    'msg_username' => '用户名：',
    'msg_passwd' => '密码：',
    'msg_ip' => 'Aipi地址：',
    'msg_group' => '群组：',
    'msg_plan' => '关税：',
    'msg_language' => '语言：',
    'msg_count_mailbox' => '邮箱数量：',
    'msg_bandwidth' => '流量：',
    'msg_count_sites' => '网站数量：',
    'msg_count_db' => 'MySQL数据库：',
    'msg_count_subdomains' => 'DNS区域数量：',
    'msg_count_dns_zones' => 'DNS区域数量：',
    'msg_count_mailperhour' => '每小时消息数量：',
    'msg_count_disk' => '磁盘空间：',
    'msg_count_ftp_acct' => 'FTP帐户：',
    'msg_shell_access' => 'shell访问：',
    'msg_owner' => '所有者：',

    'msg_seccess_added' => '成功添加',
    'msg_seccess_edit' => '成功编辑',

    'msg_only_number' => '只指定字段中的数字',
    'msg_both_num_leter' => '只指定字段中的数字或拉丁字母',

    'msg_only_number_bandwith' => '使用数字,指定带宽',
    'msg_only_number_sites' => '使用数字,指定网站的数量',
    'msg_only_number_subdomains' => '使用数字,指定子域的数量',
    'msg_only_number_databases' => '使用数字,指定数据库的数量',
    'msg_only_number_mailbox' => '使用数字,指定邮箱数量',
    'msg_only_number_mailperhour' => '使用数字,指定每小时的字母数量',
    'msg_only_number_ftp_acct' => '使用数字,指定ftp帐户的数量',
    'msg_only_number_disk' => '使用数字来指定驱动器',
    'msg_both_lang' => '指定语言',
    'msg_both_shell' => '指定要使用的外Shell',
    'msg_both_plan' => '输入资费名称',
    'msg_both_template' => '指定模板',


    'msg_everything_good' => '一切都完成没有错误',
    'msg_ip_wrong' => 'IP地址不正确',
    'msg_exists_plan' => '此资费已经存在',
    'msg_done' => '完成',
    
    'msg_done_pass' => '密码必须包含至少7个字符',
    'msg_done_username' => '用户名必须最多8个字符',

    'msg_both_username' => '使用数字和拉丁字母来指定用户名。最少3个字符',
    'msg_both_group' => '使用数字和拉丁字母来指定组的名称',
    
    'msg_no_user_sel' => '这不属于用户',
    'msg_everything' => '一切都很好',

    'msg_edit_or_add_group' => '添加新组或编辑当前→',
    'msg_edit_or_add_plan' => '添加新的资费或编辑当前→',

    'js_lang_select_ok' => '语言成功更改',

    'tpl_host_add_plan' => '添加关税计划',
    'tpl_host_edit_plan' => '编辑资费计划',
    'tpl_host_save_plan' => '保存关税计划',
    'tpl_host_add_new_plan' => '添加新的关税',
    'tpl_host_plan_name' => '资费名称：',
    'tpl_host_bandwidth' => '流量：',
    'tpl_host_disk' => '设备：',
    'tpl_host_sites' => '网站：',
    'tpl_host_subdomains' => 'DNS区域：',
    'tpl_host_databases' => '数据库：',
    'tpl_host_mailbox' => '邮箱：',
    'tpl_host_mailperhour' => '每小时的信件数量：',
    'tpl_host_ftp_acct' => 'FTP帐户：',
    'tpl_host_shell_access' => '外Shell访问：',
    'tpl_host_lang' => '语言：',
    'tpl_host_lang_noselect' => '未选择',

    'tpl_host_groups_acct' => '主机帐户组',
    'tpl_host_current_group' => '当前组：',
    'tpl_host_create_new_group' => '新建',
    'tpl_host_name_new_group' => '新组的名称：',
    'tpl_host_select_not_defined' => '未定义',
    'tpl_host_select_yes' => '开',
    'tpl_host_select_no' => '关',
    'tpl_host_select_form_save' => '保存',
    'tpl_host_select_form_del' => '删除',

    'tpl_host_list_title' => '所有主机帐户',
    'tpl_host_list_login' => '登录',
    'tpl_host_list_plan' => '关税',
    'tpl_host_list_homefolder' => '主文件夹',
    'tpl_host_list_ip' => 'IP',
    'tpl_host_list_disk' => '驾车',
    'tpl_host_list_group' => '群组',
    'tpl_host_list_control' => '管理',
    'tpl_host_list_edit' => '编辑',
    'tpl_host_list_delete' => '删除',
    'tpl_host_list_t_plan' => '关税计划',
    'tpl_host_list_t_plans' => '关税计划',

    'tpl_host_single_title' => '主机帐户信息',
    'tpl_host_single_action' => '操作：',
    'tpl_host_single_abort' => '取消',
    'tpl_host_single_create_date' => '创建日期：',
    'tpl_host_single_edit_date' => '上次修改时间：',
    'tpl_host_single_domain' => '域名',
    'tpl_host_single_ip' => 'IP',
    'tpl_host_single_home' => '主目录',
    'tpl_host_single_aliases' => '别名',
    'tpl_host_single_triger_on' => '解锁',
    'tpl_host_single_triger_off' => '阻止',
    'tpl_host_single_change_lang' => '更改语言',

    'lang_host_api' => 'API访问',
    'lang_host_apifull' => '完整API访问权限（管理员）',
    'apifull_off' => '权限不足以执行此API请求',

    'hostacc_suspended_sites' => '阻止添加,编辑,删除网站。请联系您的管理员。',
    'hostacc_del_process' => '已删除...',
    'hostacc_successf_add' => '主机帐户成功添加',

    'hostacc_change_pass_label' => '密码',
    'hostacc_change_pass_label1' => '输入新密码',
    'hostacc_change_pass_label2' => '重复新密码',
    'hostacc_change_pass_pass_diff' => '你输入的密码不匹配。',
    'hostacc_change_pass_exec' => '更改密码',
    'hostacc_change_pass_exec_ok' => '密码成功更改',

    'hostacc_refresh_user_cache' => '更新用户统计信息',
    'hostacc_refresh_user_cache_btn' => '刷新',
    'hostacc_refresh_user_cache_ok' => '用户统计信息已成功更新',

    'hostacc_user_search' => '搜索',
    'hostacc_return_main' => '←返回主机账户列表',
    'hostacc_user_search_res_empty' => '找不到',

    'hostacc_user_search_pleasewait' => '正在搜索...',

    'msg_only_number_dnz_zones' => '使用数字,指定DNS区域的数量',
    'hostacc_sel_addgroup' => '添加组',
    'hostacc_sel_addpackage' => '添加费率',
    'hostacc_noaddhostacc_yet' => '主机帐户尚未添加',
    'hostacc_no_plans' => '关税计划尚未添加',

    "Hostacc_updatecache_detail" =>"运行统计计数：网站,邮箱的数量,已用空间,FTP帐户数量,数据库的数量。",

    'hostacc_user_alreadyexist' => '具有此名称的用户已存在',
    'hostacc_user_userhaventdomain' => '尚未添加域名',
    'hostacc_user_signin' => '登录',
    'hostacc_user_signin_warning' => '当您输入选定的用户时,将从当前的用户重新绘制。 确认？',
    'hostacc_user_signin_warning_yes' => '是',
    'hostacc_user_signin_warning_no' => '否',
    'hostacc_user_signin_failed' => '授权错误。 您必须将密码重置给用户。',
    'hostacc_user_signin_process' => '授权...',
    'hostacc_user_plan_not_set' => '未指定',

    'hostacc_header_admin_param' => '任何未定义的内容都是不允许的。',
    'hostacc_header_user_param' => '任何未定义的内容都是允许的。',
    'hostacc_chache_name' => '更改名称',
    'hostacc_input_name' => '输入新名称',
    'hostacc_suc_change' => '成功完成',
    'hostacc_suc_change_empty' => '组名中为空值',
    'hostacc_error_name_group' => '标题错误',
    'hostacc_error_no_user' => '该用户不存在',
    'hostacc_confirm_userdel' => '确认用户删除',
    'hostacc_confirm_userdel_yes' => '是',
    'hostacc_confirm_userdel_no' => '否',

    'hostacc_confirm_universal_yes' => '是',
    'hostacc_confirm_universal_no' => '否',

    'hostacc_usernotexist' => '指定的用户不存在',

    'hostacc_stat_susp_sites_hint' => '网站被阻止',
    'hostacc_stat_susp_ftp_hint' => '阻止FTP',
    'hostacc_stat_susp_email_hint' => '邮件被阻止',
    'hostacc_stat_susp_cron_hint' => '克朗阻止',
    'hostacc_stat_susp_panel_hint' => '面板已锁定',
    'hostacc_stat_susp_full_hint' => '访问被完全阻止',
    'hostacc_stat_susp_reason_hint' => '阻止原因：',
    'hostacc_stat_susp_reason_hint_notset' => '未指定',
    'hostacc_incorecly_simbol' => '资费名称中的禁止字符',

    'hostacc_createjailuser' => '监狱环境',
    'hostacc_createjailuserhint' => '用户将被放置在监狱环境中以限制访问权限',

    'hostacc_jailTitle' => '配置监狱',
    'hostacc_jailStatusTitle' => '监狱Shell',
    'hostacc_jailStatusTitlePHP' => '监狱PHP',
    'hostacc_jailStatusSave' => '保存',
    'hostacc_jailStatusDesel' => '禁用所有监狱 Shell',
    'hostacc_jailStatusSel' => '启用所有监狱 Shell',
    'hostacc_jailStatusDeselPHP' => '禁用所有监狱 PHP',
    'hostacc_jailStatusSelPHP' => '启用所有监狱 PHP',
    'hostacc_jailStatusRebuild' => '应用',
    'hostacc_jailStatusSetResOk' => '监狱环境改变成功',
    'hostacc_jailStatusSetResFail' => '监狱环境没有改变',
    'hostacc_jailPHPHint' => 'PHP将在监狱环境中执行。仅适用于fastcgi桥（php-fpm）',
    'hostacc_jailnewaccShell' => '在监狱 Shell中放置新的主机帐户',
    'hostacc_jailnewaccPhp' => '在监狱 PHP中放置新的主机帐户',
    'hostacc_jailStatusAutoNewAcc' => '保存',
    'hostacc_jailStatusAutoNewAccSaveok' => '保存成功',

    'hostacc_jailerrorMountMysql' => '安装mysql套接字错误',

    'hostacc_confirmDelPlan' => '确认删除关税',
    'hostacc_limit_mysql_user' => '用户的mysql连接限制',
    'hostacc_max_questions' => 'MYSQL每小时​​请求次数限制',
    'hostacc_max_updates' => '每小时编辑数据的MYSQL限制',
    'hostacc_max_connections' => '同时连接的MYSQL限制',
    'hostacc_max_user_connections' => '每小时MYSQL用户连接限制',
    'hostacc_error_msg_questions' => '使用数字来指定max_questions',
    'hostacc_error_msg_updates' => '使用数字,指定max_updates',
    'hostacc_error_msg_user_connections' => '使用数字,输入max_user_connections',
    'hostacc_error_msg_connections' => '使用数字来指定max_connections',
    'hostacc_jailreinit' => '所有用户的监狱环境正在重新初始化。请稍等。',
    'hostacc_jailreinitParams' => '指定参数：',
    'hostacc_jailreinitParamsHost' => '设置监狱环境的状态：',
    'hostacc_jailreinitParamsPHP' => '将监狱的状态设置为php：',
    'hostacc_jailreinitParamsPHPForce' => '执行虚拟主机重建：',
    'hostacc_jailreinitParamsHostOn' => '启用',
    'hostacc_jailreinitParamsHostOff' => '禁用',
    'hostacc_jailreinitParamsHostRebuildYes' => '是',
    'hostacc_jailreinitParamsHostRebuildNo' => '否',
	


);

?>