<?php
$lang = array(
   'ipmanager_not_permishion'		=> '你没有足够的权限',
   'ipmanager_added'		=> '已增加',
   'ipmanager_error'		=> '错误：此IP已存在',
   'ipmanager_deleted'		=> '已删除',
   'ipmanager_ip_exists'		=> '此IP已存在',
   'ipmanager_error_data'		=> '输入的数据错误',
   'ipmanager_del_ip'		=> 'IP不能被删除，因为它被用户域名所使用，具有此IP的域的数量有：',
   'Ipmanager_del_ip_failed_userset'		=> '无法删除IP，已被添加到用户的IP配置，拥有此IP的用户数量有：',
   'ipmanager_done_success'		=> '成功',
   'ipmanager_not_deleted'		=> '无法删除主IP地址',
   'ipmanager_del'		=> '删除',
   'ipmanager_del_process'		=> '删除中...',
   'ipmanager_list_ip'		=> 'IP列表',
   'ipmanager_ip'		=> 'IP',
   'ipmanager_interface'		=> '连接',
   'ipmanager_managment'		=> '管理',
   'ipmanager_list6'		=> 'IPv6列表',
   'ipmanager_add_ip'		=> '添加新的IP地址',
   'ipmanager_class'		=> 'C类CIDR（例如192.168.4.128/25）',
   'Ipmanager_ip_n'		=> 'IP/掩码（例如192.168.4.128/255.255.255.128）',
   'ipmanager_ip_r'		=> 'IP地址范围（例如192.168.4.128 - 255）',
   'ipmanager_ip_adrr'		=> 'IP地址：',
   'ipmanager_masc'		=> '子网掩码：',
   'ipmanager_gaterw'		=> '网关（可选）：',
   'ipmanager_exclude'		=> '排除ip（可选）：',
   'ipmanager_add_ip_adr'		=> '添加ip地址',
   'ipmanager_add_ip_ls'		=> '正在添加IP地址，请稍等......',
   'ipmanager_pahf_carantin'		=> '隔离路径：',
   'Ipmanager_text1'		=> '<br/>（当添加一系列ipv6地址时，地址的最后一部分必须包含范围的初始和最终数值，并用连字符分隔。）示例：xxxx：xxxx：x ::<b>a-b</b>，其中<b>a</b>是范围的初始数字，并且<b>b</b> - 后缀<br/>在添加ipv6地址时，您可以在此字段中指定一个后缀，将IP地址分隔成描述网络和主机的部分。例如：<b>/32</b>在这种情况下，地址的前32位将提供给您网络，其余部分将是您提供给用户的地址或子网。默认情况下，将使用后缀/128，这对应于特定IPv6地址的描述。<br/>',
   'Ipmanager_text2'		=> '<br/>（当添加一系列ipv6地址时，在此字段中可以列出创建不合需要的地址，并用空格分隔它们。）示例：<b>xxxx:xxxx:x::a xxxx:xxxx:x::b</b><br/>这些地址将从创建的范围中排除）<br/>',

   'ipmanager_refresh_cacheips_stat'		=> '更新缓存ip',
   'ipmanager_refresh_cacheips_stat_wait'		=> 'IP缓存已更新',
   'ipmanager_ips_stat'		=> '免费',
   'ipmanager_error_data_wrongip'		=> '无效的IP地址格式',
   'ipmanager_no_ip'		=> '没有IP地址',
   'ipmanager_nat_ok'		=> '已成功添加关联的IP NAT，虚拟主机已更新',
   'ipmanager_nat_error'		=> '添加IP NAT错误',
   'ipmanager_nat_error0'		=> '添加IP NAT错误，这个设备已经存在',
	
); 