<?
$lang = array(
    'logging'		=> '日志记录',
    'logging_log'		=> '日志记录',
    'logging_select_user'		=> '选择用户：',
    'logging_not_selected'		=> '未选中',
    'logging_setting_rotation'		=> '配置日志跳转 →',
    'logging_users_log'		=> '自定义存档日志',
    'logging_download'		=> '下载',
    'logging_download_log'		=> '下载这篇日志',
    'logging_download_all_log'		=> '下载当前日志',
    'logging_path_log'		=> '日志文件的路径：',
    'logging_searche_log'		=> '在日志中搜索短语：',
    'logging_show'		=> '显示',
    'logging_prev_record'		=> '上一个条目',
    'logging_next_record'		=> '下一个条目',
    'logging_line_latest'		=> '行（从最后一行开始）',
    'logging_line_display'		=> '要显示多少行：',
    'logging_add_log_rotation'		=> '将日志添加到',
    'logging_back_log'		=> '← 返回记录',
    'logging_not_install'		=> '未安装',
    'logging_install'		=> '安装',
    'logging_successfully'		=> '成功安装，刷新页面',
    'logging_stat_ins'		=> '有效',
    'logging_nologs'		=> '没有可用的日志',
    'logging_titlemanrot'		=> '控制',
    'logging_namelog'		=> '记录名称',
    'logging_titlelog1'		=> '记录',

    'logging_rotUserLogsTitle'		=> '用户日志',
    'logging_rotUserLogsHint'		=> '在存档中执行上个月的日志压缩，如果处于活动状态，则在执行cron_log cron任务之后执行启动',

    'logging_ConfPeriod' => '发布期',
    'logging_ConfPeriodHourly' => '每小时一次',
    'logging_ConfPeriodDaily' => '每一天',
    'logging_ConfPeriodWeekly' => '每周',
    'logging_ConfPeriodMonthly' => '每个月',
    'logging_ConfSave' => '保留',
    'logging_ConfSaveAllUser' => '适用于所有用户',
    'logging_ConfCountCountLogs' => '保留旧日志的数量',
    'logging_ConfCountCountLogsPlace' => '输入数字',
    'logging_ConfCompress' => '压缩',
    'logging_ConfFormat' => '名称格式',
    'logging_ConfFormatDate' => '日期',
    'logging_ConfFormatNumber' => '序号',
    'logging_ConfUserTitleConfigure' => '设置用户日志轮换',

    'logging_activeServiceLog' => '记录日志',
    'logging_confLogrotSaveok' => '保存成功',
    'logging_confLogrotEnDisOk' => '保存成功',
);