<?php

$lang = array (
   'mailserver'		=> '邮箱服务器',
   'sendserver'		=> '发送邮件服务器',
   'receiveerver'		=> '接收邮件服务器',
   'customazing'		=> '设置',
   'version'		=> '版本',
   'installed'		=> '已安装',
   'install'		=> '安装',
   'delete'		=> '删除',
   'reinstall'		=> '重新安装',
   'stop'		=> '停止',
   'start'		=> '运行',
   'restart'		=> '重新启动',
   'send'		=> '发送',
   'mailserver_incl'		=> '启用',
   'mailserver_off'		=> '禁用',
   'mailserver_queue_close'		=> '关闭',
   'mailserver_queue_delete'		=> '清除队列',
   'mailserver_queue_delete_force'		=> '强行清除队列',
   'mailserver_queue_delete_frozen'		=> '删除被冻结的队列',
   'mailserver_queue_delete_ok'		=> '已成功清理队列',
   'mailserver_queue_delete_progress'		=> '正在清除队列，请稍等',
   'mailserver_queue_count_mess'		=> '队列中的消息数量：',
   'mailserver_queue_mess_resend'		=> '重新发送',

   'mailserver_reject_remote_mail'		=> '拒绝发送到服务器的邮件',
   'mailserver_reject_spf'		=> 'SPF失败时拒收邮件',
   'mailserver_reject_bounce'		=> '超过配额时拒绝用户邮件',
   'mailserver_reject_smtp_sender'		=> '设置发件人标题的SMTP验证',

   'msg_mail_no_admin'		=> '没有足够的权限',
   'msg_mail_remove_all'		=> '删除所有',
   'msg_mail_progress_txt'		=> '进行中...',
   'msg_mail_module_on'		=> '启用',
   'msg_mail_module_off'		=> '禁用',

   'mailserver_custom_save'		=> '更新bleckers列表',
   'mailserver_list_msg'		=> '邮件列表',
   'mailserver_not_list_msg'		=> '邮件列表为空。',
   'mailserver_count_msg'		=> '邮件数量',
   'mailserver_not_id_msg'		=> '缺少电子邮件ID',
   'mailserver_not_server_send'		=> '缺少或不正确的邮件服务器',
   'mailserver_request_succecf'		=> '已完成请求',
   'mailserver_not_dell_force'		=> '邮件服务器不支持强制删除',
   'mailserver_not_dell_frozen'		=> '邮件服务器不支持删除冻结邮件',
   'mailserver_limit_send'		=> '每小时发送信件的限制：',
   'mailserver_save'		=> '保存',
   'mailserver_list_black'		=> '管理自定义RBL',
   'mailserver_start_ok'		=> '已启动',
   'mailserver_stop_ok'		=> '已停止',
   'mailserver_start_failed'		=> '运行完成并显示错误',
   'mailserver_no_queue'		=> '队列中没有消息',

   'mailserver_qualify_domain_title'		=> '配置qualify_domain',
   'mailserver_qualify_domain_hint'		=> '要使用不带标题的邮件功能发送带签名的DKIM、SPF的信件，您需要在qualify_domain中指定一个具有DKIM或SPF记录的域名',
   'mailserver_qualify_label'		=> 'qualify_domain值',
   'mailserver_qualify_save'		=> '保存',
   'mailserver_qualify_save_failed'		=> '无效的域名格式。',
   'mailserver_qualify_save_ok'		=> '保存成功，该服务将重新启动。',
   'mailserver_max_size_out_message'		=> '字母Mb的最大大小',
   'mailserver_error_format_number'		=> '格式错误，必须是数字',
   'mailserver_success'		=> '成功',

);
