<?php

$lang = array (
	'mailclient' => '邮箱',
	'on' => '开启',
	'off' => '关闭',
	'status_on' => '包括',
	'status_off' => '关闭',
	
	'tpl_mail_autoanswer' => '自动回复者',
	'tpl_mail_user' => '用户',
	'tpl_mail_box' => '输入框',
	'tpl_mail_interval' => '间隔',
	'tpl_mail_from' => '发件人',
	'tpl_mail_subject' => '主题',
	'tpl_mail_body_mail' => '邮件正文',
	'tpl_mail_action' => '操作',
	'tpl_mail_is_active' => '有效',
	'tpl_mail_add' => '添加',
	'tpl_mail_del' => '删除',
	'tpl_mail_edit' => '编辑',
	'tpl_mail_save' => '保存',
	'tpl_mail_abort' => '取消',

	'tpl_mail_antivir_control' => '防病毒管理',
	'tpl_mail_antivir_status' => '状态：',
	'tpl_mail_on' => '启用',
	'tpl_mail_off' => '禁用',
    'tpl_mail_tools'		=> '设置',

	'tpl_mail_account' => '邮件帐户',
	'tpl_mail_account_add' => '添加帐户',
	'tpl_mail_account_box' => '帐户',
	'tpl_mail_passwd' => '密码',
	'tpl_mail_quota' => '配额',
	'tpl_mail_email' => '电子邮件',
	'tpl_mail_email_mail' => '邮件',
	'tpl_mail_enter_passwd' => '输入密码',
	'tpl_mail_open_roundcube' => 'Roundcube',
	'tpl_mail_open_squire' => 'Squiremail',
	'tpl_mail_open_webmail' => 'Webmaillite',

	'tpl_mail_webmail' => 'Webmail',

	'tpl_mail_email_default' => '默认邮箱',
	'tpl_mail_domain' => '域名',
	'tpl_mail_not_install' => '未安装',
	'tpl_mail_jmp_email' => '转发至电子邮件',
	'tpl_mail_jmp_to' => '转发至',
	'tpl_mail_jmp_email' => '转发至电子邮件',
	'tpl_mail_jmp_email_all' => '转发邮件',
	'tpl_mail_jmp_domain_all' => '域名重定向',
	'tpl_mail_enter_email' => '输入电子邮件',
	'tpl_mail_failed_delivery' => '无法投放',
	'tpl_mail_blackhole' => '黑洞',

	'tpl_mail_service_noinst' => '服务未安装',
	'tpl_mail_service_norun' => '服务未启动',
	'tpl_mail_service_control' => '服务管理',

	'tpl_mail_record_add' => '添加条目',
	'tpl_mail_jmp_domain2from' => '要重定向的域名',
	'tpl_mail_jmp_email2to' => '要发送的邮件',
	'tpl_mail_jmp_box_all' => '箱子转发',
	'tpl_mail_jmp_box_source' => '从中重定向的电子邮件',
	'tpl_mail_jmp_box_target' => '要发送的电子邮件（可以是多个,用逗号分隔）',
	'tpl_mail_jmp_box_target_save' => '将邮件保存在源邮箱中（应该在邮件帐户部分创建）？',
	'tpl_mail_jmp' => '重定向',

	'tpl_mail_control_opendkim' => '管理opendkim',
	'tpl_mail_control_clamav' => '管理clamav',
	'tpl_mail_control_spam' => '管理Spamassassin',
	'tpl_mail_enter_to_email' => '登录到邮箱',
	'tpl_mail_fine_tuning' => '微调',
	'tpl_mail_options' => '选项',
	'tpl_mail_status' => '状态',
	'tpl_mail_filter' => '邮件过滤',
	'tpl_mail_filter_control' => '管理筛选器',
	'tpl_mail_filters' => '筛选器',
	'tpl_mail_control' => '管理',
	'tpl_mail_mass_install' => '批量安装',
	'tpl_mail_control_queue' => '队列管理',
	'tpl_mail_control_spf' => '管理SPF',
	'tpl_mail_filter_name' => '筛选器命名',
	'tpl_mail_rules' => '规则',
	'tpl_mail_filter_header' => '筛选器',
	'tpl_mail_rules'		=> 'Правила',
	'tpl_mail_filter_header'	=> 'Фильтр',
	
	'tpl_mail_rules_from' => '发件人',
	'tpl_mail_rules_subject' => '主题',
	'tpl_mail_rules_to' => '收件人',
	'tpl_mail_rules_reply' => '被访者',
	'tpl_mail_rules_bodytest' => '信的正文',
	'tpl_mail_rules_any_header' => '任何标题',
	'tpl_mail_rules_any_recipient' => '任何收件人',
	'tpl_mail_rules_no_deviver' => '未发送',
	'tpl_mail_rules_error' => '包含错误',
	'tpl_mail_rules_id' => '队列中的ID',
	'tpl_mail_rules_status' => '垃圾邮件状态',
	'tpl_mail_rules_bar' => '垃圾邮件等级',
	'tpl_mail_rules_scope' => '垃圾邮件量',

	'tpl_mail_rules_contains' => '包含',
	'tpl_mail_rules_match' => '匹配',
	'tpl_mail_rules_no_contains' => '不包含',
	'tpl_mail_rules_equals' => '等于',
	'tpl_mail_rules_begin' => '开始于',
	'tpl_mail_rules_end' => '结束于',
	'tpl_mail_rules_no_begin' => '不以1开始',
	'tpl_mail_rules_no_end' => '不结束',
	'tpl_mail_rules_no_match' => '不匹配',
	'tpl_mail_rules_above' => '更多（数字）',
	'tpl_mail_rules_no_above' => '没有更多（数字）',
	'tpl_mail_rules_below' => '少于（数字）',
	'tpl_mail_rules_no_below' => '不少于（数字）',

	'tpl_mail_rules_discrab' => '拒绝',
	'tpl_mail_rules_redirect' => '重定向',
	'tpl_mail_rules_fail' => '失败',
	'tpl_mail_rules_stop' => '停止筛选器',
	'tpl_mail_rules_deliver' => '放入文件夹',
	'tpl_mail_rules_pipe' => '转发到节目',

	'tpl_mail_mass_install_prog' => '批量软件安装',
	'tpl_mail_setup' => '安装',
	'tpl_mail_more' => '更多信息',
	'tpl_mail_hide' => '隐藏',

	'tpl_mail_message_time' => '时间',
	'tpl_mail_message_id' => '消息ID',
	'tpl_mail_message_sources' => '发件人',
	'tpl_mail_message_target' => '收件人',
	'tpl_mail_message_size' => '大小',
	'tpl_mail_message_status' => '状态',
	'tpl_mail_message_action' => '操作',
	'tpl_mail_message_queue' => '队列',

	'tpl_mail_receive_name' => '配置传入邮件服务器',
	'tpl_mail_receive_installed' => '已安装',
	'tpl_mail_receive_working' => 'Works',
	'tpl_mail_receive_more' => '详情',
	'tpl_mail_receive_hide' => '隐藏',
	'tpl_mail_receive_install' => '安装',
	'tpl_mail_receive_delete' => '删除',
	'tpl_mail_receive_reinstall' => '重新安装',
	'tpl_mail_receive_start' => '运行',
	'tpl_mail_receive_stop' => '停止',
	'tpl_mail_receive_restart' => '重新启动',

	'tpl_mail_email_clients' => '邮件客户',

	'tpl_mail_send_name' => '发送服务器配置',
	'tpl_mail_send_warning' => '安装时,Exim的外发邮件服务器将被删除',
	'tpl_mail_send_postfix' => '后缀',
	'tpl_mail_send_exim' => '进出口',
	'tpl_mail_send_warning_postfix' => '安装时,发送邮件服务器Postfix将被删除',
	'tpl_mail_send_dkim' => 'OpenDKIM',
	'tpl_mail_send_dmarc'		=> 'OpenDMARC',
	'tpl_mail_send_antispam' => '反垃圾邮件',
	'tpl_mail_send_antivirus' => '反病毒',

	'tpl_mail_spf_control' => '管理SPF',
	'tpl_mail_dmarc_control'	=> '管理DMARC',
	
	'tpl_mail_spf_select_user' => '选择用户',
	'tpl_mail_spf_no_domain' => '没有可用域名',
	'tpl_mail_spf_domain' => '域名',
	'tpl_mail_spf_action' => '操作',
	'tpl_mail_spf_saved' => '记录',
	'tpl_mail_dmarc_select_user'	=> 'Выберите пользователя',
	'tpl_mail_dmarc_no_domain'	=> 'Нет доступных доменов',
	'tpl_mail_dmarc_domain'		=> 'Домен',
	'tpl_mail_dmarc_action'		=> 'Активация',
	'tpl_mail_dmarc_jmp'		=> 'Действие',
	'tpl_mail_dmarc_mailto'		=> 'Адрес для отчетов',
	'tpl_mail_dmarc_saved'		=> 'Запись',
	
	'tpl_mail_rouncube' => 'Rouncube',
	'tpl_mail_webmaillite' => 'WebMailLite',

	'msg_mail_err_mysql_connect' => '连接到MySQL服务器时出错：',
	'msg_mail_webmail' => 'Webmail',
	'msg_mail_delete' => '删除',
	'msg_mail_process_ok' => '流程成功',
	'msg_mail_process_last_log' => '执行命令的最后一行：',
	'msg_mail_not_your_domain' => '这不是你的域名',
	'msg_mail_enter_def_action' => '指定默认操作',
	'msg_mail_enter_email' => '输入邮箱',
	'msg_mail_process_ok' => '操作成功',
	'msg_mail_choose_user' => '选择用户',
	'msg_mail_enter_domain' => '输入域名',
	'msg_mail_already_domain' => '此域名已存在',
	'msg_mail_chouse_option' => '指定一个选项',
	'msg_mail_already_autoanswer' => '应答机已存在',
	'msg_mail_enter_time' => '指定时间',
	'msg_mail_enter_text' => '输入文字',
	'msg_mail_enter_subject' => '主题',
	'msg_mail_enter_body' => '信的正文',
	'msg_mail_ver_txt' => '版本：',

	'msg_mail_run' => '已启动',
	'msg_mail_stoped' => '已停止',
	'msg_mail_success_edit' => '编辑成功',

	'js_mail_process_progress' => '安装正在进行中,请稍候。',
	'js_mail_process_finish' => '流程已完成',
	'js_mail_not_install' => '未安装',

	'js_mail_wrong_pass' => '密码错误！',
	'js_mail_client_prog' => '你想安装邮件客户端',
	'js_mail_progress' => '进行中...',
	'js_mail_process_on' => '启用',
	'js_mail_process_off' => '已禁用',
	'js_mail_email_error' => '输入正确的邮箱',
	'js_mail_passwd_error_len' => '密码不能为空',
	'js_mail_err_source_domain' => '请输入有效的起始网域',
	'js_mail_err_target_domain' => '输入正确的目标域',
	'js_mail_err_source_email' => '请输入一个有效的初始邮箱',
	'js_mail_err_target_email' => '输入正确的目标邮箱',
	'js_mail_err_already' => '域名/邮箱 已经在列表中',
	'js_mail_jmp_to' => '转发至',
	'mailclient_del_process' => '已删除...',

	'mailclient_emailexist' => '邮箱已存在',
	'mailclient_invalid_comand' => '不合适的团队',
	'mailclient_status' => '状态',
	'mailclient_command_succsecfully' => '命令已完成',

    "mailclient_addmail_failed_overlimit" => "超出邮件帐户限制：邮件帐户的最大数量",
    "mailclient_addmail_failed_quotaformat" => "配额格式无效。",
    "mailclient_spf_addemail" => "SPF",
    "mailclient_dkim_addemail" => "DKIM",
	"mailclient_dmarc_addemail"=>"DMARC",
    "mailclient_new_quota" => "新配额,mb",
    "mailclient_new_pass" => "新密码",
    "mailclient_change_quota" => "更改配额",
    "mailclient_change_pass" => "更改密码",
    "mailclient_change_pass_quota" => "更改密码,配额",
    "mailclient_change_auto_text" => "更改文字",
    "mailclient_change" => "保存",
    "mailclient_successfully_done" => "成功",
    "mailclient_no_rights" => "您没有足够的权限来执行此操作",
    "mailclient_empty_field" => "该字段必须填写",

    "mailclient_usernothaveemailbox" => "用户没有邮箱",
    "mailclient_usernothaveredirect" => "用户没有添加重定向",
    "mailclient_user_nothavesites" => "用户没有任何添加的网站",

    "mailclient_autoresponder" => "启用自动回复",
    "mailclient_text_autoresponder" => "输入答录机的文字",
    "mailclient_error_number" => "不是正确的值格式",
    "mailclient_not_text" => "消息文本必须填写",
    "mailclient_autoresponder_check" => "自动回复",
    "mailclient_autoresponder_text" => "消息文本",
    "mailclient_data_not_corected" => "无效数据",
    "mailclient_change_text" => "编辑文本",
    "mailclient_change_text_check" => "确认",
    "mailclient_change_succecfully" => "成功修改数据",
    "mailclient_status" => "启用",
    "mailclient_saving" => "正在保存",
    "mailclient_loging" => "邮件日志",
    "mailclient_load_statistic" => "下载统计数据",
    "mailclient_not_email" => "用户没有邮箱",
    "mailclient_not_email_statistic" => "不幸的是,今天还没有统计数据",
    "mailclient_statistic" => "收发信件统计",
    "mailclient_filter" => "邮件筛选器",
    "mailclient_email_filter" => "选择邮箱",
    "mailclient_filter_name" => "筛选器名称",
    "mailclient_filter_condition" => "过滤条件",
    "mailclient_filter_act" => "筛选器操作",
    "mailclient_filter_create" => "创建筛选器",
    "mailclient_filter_ot" => "来自",
    "mailclient_filter_tema" => "主题",
    "mailclient_filter_do" => "请执行",
    "mailclient_filter_reply" => "回复",
    "mailclient_filter_text" => "文本",
    "mailclient_filter_any_title" => "任何标题",
    "mailclient_filter_not_previously_delivered" => "以前未送达",
    "mailclient_filter_error_message" => "这是一条错误消息",
    "mailclient_filter_ind_list" => "列表IDU",
    "mailclient_filter_state_spam" => "垃圾电子邮件状态",
    "mailclient_filter_junk_mail" => "垃圾邮件面板",
    "mailclient_filter_spam_evaluation" => "垃圾电子邮件评估",
    "mailclient_filter_contains" => "包含",
    "mailclient_filter_regex" => "对应于正则表达式",
    "mailclient_filter_not_contains" => "不包含",
    "mailclient_filter_equal" => "等于",
    "mailclient_filter_starts" => "以...开头",
    "mailclient_filter_end" => "结束",
    "mailclient_filter_not_starts" => "它不启动",
    "mailclient_filter_not_end" => "不以...结尾",
    "mailclient_filter_not_equal" => "不匹配",

    "mailclient_filter_dell_message" => "删除留言",
    "mailclient_filter_redirect" => "重定向",
    "mailclient_filter_error_mes" => "错误消息",
    "mailclient_filter_leave_processing_rules" => "离开处理规则",
    "mailclient_filter_deliver_folder" => "传送到文件夹",
    "mailclient_not_user" => "用户不匹配",
    "mailclient_name_filter" => "筛选名称无效至少5个字符（a-z0-9_）",
    "mailclient_not_filter_1" => "筛选不匹配1",
    "mailclient_not_filter_2" => "筛选不匹配2",
    "mailclient_not_action" => "不存在操作",
    "mailclient_not_text_filter" => "文本筛选器不匹配",
    "mailclient_not_email_reg" => "电子邮件与正则表达式不匹配",
    "mailclient_folder" => "测试/垃圾邮件 - 电子邮件目录中的文件夹和文件名",
    "mailclient_error_folder" => "目录与正则表达式不匹配",
    "mailclient_email_redirect" => "重定向电子邮件",
    "mailclient_not_filter_include" => "没有安装筛选器",
    "mailclient_n_filter" => "筛选名称",
    "mailclient_filter_header_all" => "所有筛选",
    "mailclient_filter_header_add" => "添加筛选",


    "mailclient_action" => "操作",
    "mailclient_description_text" => "* *警告：当为文本组成一个筛选器时,请记住所有的标题和消息主体都被检查完整。",
    "mailclient_description_filter" => "说明",
    "mailclient_description_tema" => "* *警告：一些邮件服务器根据字符的长度对邮件的主题进行编码,在编写筛选器时考虑到这一点。",
    "mailclient_description_text2" => "**一些邮件服务器对Content-Transfer-Encoding消息的主体进行编码：base64在这种情况下,用户筛选器毫无意义。",
    "mailclient_description2" => "*具有相同名称的筛选器将被创建的筛选器覆盖。",
    "mailclient_description3" => "**过滤器的顺序很重要。 过滤器从上到下执行（筛选“删除消息”后，具有相同条件的更多过滤器将不起作用）",
    "mailclient_mailing" => "邮件列表",


    "mailclient_not_group" => "没有订户列表",
    "mailclient_add_group" => "添加订户列表",
    "mailclient_group_mailing_name" => "列表名称",
    "mailclient_group_mailing_description" => "列表说明",
    "mailclient_num_piople" => "人数",
    "mailclient_view_list" => "管理列表",
    "mailclient_view" => "查看",
    "mailclient_remove_group" => "删除列表",
    "mailclient_add_in_list" => "添加到列表",
    "mailclient_error_group" => "列表名称与正则表达式不匹配",
    "mailclient_group_file_suceesuele" => "成功创建的订阅者列表",
    "mailclient_error_group_file" => "列表名称已存在",
    "mailclient_name_user" => "订户名称",
    "mailclient_name_user2" => "订户名称",
    "mailclient_phone" => "电话",
    "mailclient_address" => "地址",
    "mailclient_not_data" => "不适用于数据",
    "mailclient_name_user_error" => "订户的姓名或姓氏与正则表达式不匹配",
    "mailclient_phone_error" => "电话号码与正则表达式不匹配",
    "mailclient_address_error" => "地址与正则表达式不匹配",
    "mailclient_not_all_data" => "无所有值",
    "mailclient_group_mailing_none" => "订阅者列表为空",
    "mailclient_field" => "列",
    "mailclient_not_email_parser" => "不幸的是,解析器没有找到电子邮件订阅者",
    "mailclient_not_file_prepere" => "缺少数组处理文件",
    "mailclient_num_equal" => "匹配数量 - ",
    "mailclient_num_black_list" => "黑名单中的订阅者 - ",
    "mailclient_num_error" => "错误数量 - ",
    "mailclient_add_users" => "新增订阅者 - ",
    "mailclient_error_file_data" => "禁止的数据类型 - ",
    "mailclient_error_file_save" => "无法保存文件",
    "mailclient_parse_email" => "此电子邮件存在",
    "mailclient_succes_remove" => "订阅者列表已成功删除。",
    "mailclient_subscription" => "签名",
    "mailclient_subscription_send" => "状态",
    "mailclient_subscription_data" => "订阅日期",
    "mailclient_not_number" => "不是数字",
    "mailclient_not_file" => "没有要编辑的文件",
//    "mailclient_group_time_start" => "启动时间00:00",
//    "mailclient_group_time_start2" => "启动时间",
//    "mailclient_error_description" => "描述与正则表达式不匹配",
//    "mailclient_error_time_start" => "启动时间与正则表达式不匹配",
//    "mailclient_start" => "启动",
//    "mailclient_start_mail" => "启动邮件列表",

    "mailclient_save_changes" => "保存更改",
    "mailclient_add_user" => "添加订户",
    "mailclient_email_user" => "电子邮件订户",

    "mailclient_add_user_header" => "添加订阅者",
    "mailclient_add_user_process_header" => "添加订阅者",
    "mailclient_error_active" => "操作不符合正则表达式",
//    "mailclient_error_active" => "电子邮件必须填写",
    "mailclient_succesfulle_add_user" => "订阅者已成功添加。",
    "mailclient_error_add_user" => "保存订阅时出错,可能没有列表。",


    "mailclient_remove_succesfully" => "订阅者已成功删除。",
    "mailclient_remove_send" => "订阅者退订邮件列表",
    "mailclient_add_send" => "订阅邮件列表的订阅者",
    "mailclient_add_black_list" => "黑名单",
    "mailclient_add_black_list_succ" => "添加到黑名单中",
    "mailclient_add_black_list_succ_user" => "订阅者在黑名单上",
    "mailclient_list_send" => "邮件列表",
    "mailclient_mail" => "信件",

    "mailclient_text_1" => "发送邮件时被覆盖的值",
    "mailclient_text_name" => '{$name}是用户的名字',
    "mailclient_text_email" => '{$email} - 电子邮件订阅者',
    "mailclient_text_last_name" => '{$lastname} - 用户姓氏',
    "mailclient_text_phone" =>'{$phone} - 用户手机',
    "mailclient_text_address" =>'{$address} - 用户地址',
    "mailclient_user_variable" =>' - 用户变量',
    "mailclient_text_unsubscribe" =>'取消订阅',
    "mailclient_message_mailing" =>'发送名单',
    "mailclient_message_not" =>'您没有任何电子邮件',
    "mailclient_message_thema" =>'信件的主题',
    "mailclient_message_body" =>'信件正文',
    "mailclient_message_from" =>'来自谁',
    "mailclient_error_thema" =>'消息的主题与正则表达式不匹配',
    "mailclient_message_list" =>'字母列表',
    "mailclient_add_message" =>'添加电子邮件',
    "mailclient_error_id" =>'消息ID与正则表达式不匹配',
    "mailclient_piople" =>'人',
    "mailclient_add_new_message" =>'添加新消息',
    "mailclient_edit_message" =>'编辑信息',
    "mailclient_create_mailling" =>'创建简报',
    "mailclient_select_mail" =>'选择要分发的邮件',
    "mailclient_select_group_mailing" =>'选择邮件列表',
    "mailclient_email_output" =>'选择邮件列表',
    "mailclient_test_mail" =>'测试信件',
    "mailclient_email_recipient" =>'收件人的电子邮件',
    "mailclient_create_mailling_cron" =>'创建简报',
    "mailclient_send_now" =>'立即发送',
    "mailclient_send_succec" =>'邮件成功发送',
    "mailclient_add_mailing_send" =>'邮件分发已添加到任务',
    "mailclient_send_error" =>'发送电子邮件出错',
    "mailclient_send_mailing" =>'发送邮件',
    "mailclient_send_data" =>'出发日期',
    "mailclient_letter_list" =>'信，列表',
    "mailclient_mailing_id" =>'分配ID',
    "mailclient_send_status" =>'状态',
    "mailclient_num_piople_mailing" =>'邮件列表中的人',
    "mailclient_send_email" =>'发送的电子邮件总数',
    "mailclient_open_email" =>'打开',
    "mailclient_delivered_email" =>'已交付',
    "mailclient_not_send_email" =>'封锁',
    "mailclient_date" =>'日期',
    "mailclient_send_later" =>'稍后发送',
    "mailclient_send" =>'发送',
    "mailclient_succec_remove" =>'成功删除',
    "mailclient_send_ok" =>'已发送',
    "mailclient_send_not" =>'封锁',
    "mailclient_send_expectation" =>'等待发送',
    "mailclient_not_message" =>'没有要发送的消息',
    "mailclient_not_list_group" =>'没有订户列表',
    "mailclient_data_time" =>'服务器上的日期和时间',
    "mailclient_not_ecvaldata_time" =>'指定的时间少于服务器上的时间。',
    "mailclient_autocorrect" =>'只有当电子邮件存在于所选收件人列表中时,AutoChange变量才有效。',
    "mailclient_attentconfonseroff" =>'注意！服务未启动,但其部分包含在配置中 - 这可能会导致邮件操作不正确。使用下面的按钮启动该服务或将其从配置中删除',
    "mailclient_used_total_message" =>'已用MB数/总MB数/帖',
    "mailclient_overquota" =>'超出配额',
    "mailclient_dbconnfailedbrainysql" =>'连接到MySql数据库服务器时出错',
    "mailclient_no_domains" =>'没有添加域名',
    "mailclient_please_wait" =>'请稍候。',
    "mailclient_view_list_header" =>'列表视图',
    "mailclient_list_header" =>'订阅者列表',


    "mailclient_add_single_user" =>'添加一个用户',
    "mailclient_file_import" =>'从文件导入',
    "mailclient_copy_insert" =>'复制/粘贴',

    "mailclient_add_user_text_line1" =>'来自新行的每个订户',
    "mailclient_add_user_text_line2" =>'作为一个用户的数据分隔符，来自|，;的任何字符：',
    "mailclient_add_user_text_line3" =>'你可以有.txt,.csv。',
    "mailclient_add_user_text_line4" =>'对于普通的西里尔文操作,将文件保存为utf8编码。',
    "mailclient_add_user_text_placeholder" =>'ivanivanov@gmail.com; Ivan; Ivanov;其他数据',

    "mailclient_mailing_header" =>'邮件',
    "mailclient_mailing_details_header" =>'发送详情',
    "mailclient_links_header" =>'链接转到',
    "mailclient_create_mailing_header" =>'创建简报',
    "mailclient_mailing_date_header" =>'选择日期和时间',
    "mailclient_create_message" =>'创建邮件',
    "mailclient_create_list_mailing" =>'创建邮件列表',
    "mailclient_open" =>'打开',

	'mailclient_all_links' => '所有链接',
	'mailclient_links' => '链接',
	'mailclient_coversions' => '转换',

	'mailclient_each_recipient_header' => '每个收件人的更多详细信息',

	'mailclient_authmailok' => '成功登录',
	'mailclient_customdomain' => '自定义域名',
	'mailclient_customdomain_hint' => '输入网域',
	'mailclient_customdomain_failedformat' => '任意域名格式无效。',

	'mailclient_clamav_autostart' => '自动备份',
	'mailclient_confirm_remove_email' => '确认删除邮件帐户',
	'mailclient_add_email' => '添加邮箱',
	
	'mailclient_qualify_domain_title' => '配置外发邮件',
    'mailclient_qualify_domain_hint' => '要使用不带标题的邮件功能发送带有签名DKIM，SPF的字母，您需要在qualify_domain中指定一个域，该域具有DKIM，SPF记录',
    'mailclient_qualify_label' => 'Qualify_domain值',
    'mailclient_qualifyCantSetQualifyNotJail' => '无法更改qualify_domain。 用户不在监狱环境中。 请联系管理员.' ,
    'mailclient_not_quality_domain' => '配置文件中没有qualify_domain',
    'mailclient_qualify_save_failed' => '域格式无效.',
    'mailclient_qualify_save_ok' => '保存成功.',
	

);
