<?php

$lang = array(
    'msg_js_mysql_status' 	=> '无法工作',
    'msg_mysql_error_num_db' 	=> '错误，你已经达到了最大数量的基数。',
    'msg_mysql_ok_priv' 	=> '应用特权',
    'msg_mysql_err_check_db' 	=> '数据库验证错误',
    'msg_mysql_err_check_user' 	=> '检查用户名错误',
    'msg_mysql_ok_user_del' 	=> '已成功删除用户',
    'msg_mysql_err_user_del' 	=> '用户名无效',
    'msg_mysql_ok_db_del' 	=> '已成功删除数据库',
    'msg_mysql_err_db_del' 	=> '删除数据库时出错',

    'tpl_remove_delete' 	=> '删除',
    'tpl_remove_configure' 	=> '配置',
    'tpl_main_menu_mysql' 	=> 'MySql',
    'tpl_main_menu_process' 	=> 'MySql 进程列表',
    'tpl_mysql_nomysql' 	=> '未设置',
    'tpl_mysql_nomyadmin' 	=> '未设置',
    'tpl_mysql_more' 	=> '更多信息',
    'tpl_mysql_hidden' 	=> '隐藏',
    'tpl_mysql_status_info' 	=> 'MySql 状态：',
    'tpl_mysql_cnf_save' 	=> '保存',
    'tpl_mysql_install_phpadmin' 	=> '安装phpMyAdmin',
    'tpl_mysql_phpadmin_status' 	=> 'Phpmyadmin状态',
    'tpl_mysql_myadmin_install' 	=> '安装',
    'tpl_mysql_nodb' 	=> '没有添加数据库',
    'tpl_mysql_add_user' 	=> '添加用户',
    'tpl_mysql_add_db' 	=> '添加数据库',
    'tpl_mysql_jmp_promptly' 	=> '立即转到phpMyAdmin',
    'tpl_mysql_jmp_pass' 	=> '使用密码转到phpMyAdmin',
    'tpl_mysql_jmp_only' 	=> '转到phpMyAdmin',
    'tpl_mysql_select_all' 	=> '全部标记',
    'tpl_mysql_external_access' 	=> '打开外部访问',
    'tpl_mysql_external_access_all' 	=> '打开对任何IP的外部访问',
    'tpl_mysql_no_user' 	=> '没有用户添加',

    'tpl_mysql_no_user_select' 	=> '没有用户',
    'tpl_mysql_no_base_select' 	=> '没有数据库',

    'tpl_mysql_hide' 	=> '隐藏',
    'tpl_mysql_name' 	=> 'MySQL',
    'tpl_mysql_version' 	=> 'MySql 版本：',
    'tpl_mysql_reinstall' 	=> '重新安装',
    'tpl_mysql_for_expert' 	=> '对于专家',
    'tpl_mysql_for_user' 	=> '对于用户',
    'tpl_mysql_passwd_rename' 	=> '密码更改过程正在进行中。请稍等。',
    'tpl_mysql_update' 	=> '更新',
    'tpl_mysql_update_force' 	=> '强制更新',

    'js_mysql_delete' 	=> '执行删除...',
    'js_mysql_install' 	=> '执行安装...',
    'js_mysql_passwd_file' 	=> '请填写密码字段',
    'js_mysql_install_pass' 	=> '安装完成',
    'js_mysql_remove_pass' 	=> '卸载完成',
    'js_mysql_no_install' 	=> '未安装',
    'js_mysql_no_error' 	=> '没有错误',
    'js_mysql_error' 	=> '错误：',
    'js_mysql_process_done' 	=> '进程正在等待...',
    'js_mysql_check_msg' 	=> '更改密码的过程正在进行中，不要更改mysql服务器',
    'js_mysql_server_notwork' 	=> 'Mysql服务器不起作用。请联系管理员',
    'js_mysql_db_noconnect' 	=> '连接到数据库时出错。请联系管理员',
    'js_mysql_db_nodata' 	=> '数据传输发生错误。稍后再试。',
    'js_mysql_db_nodata_nopass' 	=> '新密码不能为空。请输入新密码。',
    'js_mysql_passwd_root' 	=> 'mysql root密码已被更改',
    'js_mysql_change_config' 	=> 'mysql服务器配置已更改',
    'js_mysql_restore_config' 	=> '默认配置已恢复',
    'mysql_show_all_users' 	=> '显示所有用户',
    'mysql_show_error_users' 	=> '用户数组是空的',
    'mysql_show_error_root' 	=> '你没有足够的权利。删除user_edit',
    'mysql_show_all_db' 	=> '输出用户数据库',
    'mysql_show_error_db' 	=> '基数组是空的',
    'mysql_name_user_db_error' 	=> '用户名是空的',
    'mysql_pwd_user_db_error' 	=> '数据库用户的密码为空。',
    'mysql_not_name_db' 	=> '数据库名称必须填写。',
    'mysql_add_user_ok' 	=> '用户添加。',
    'mysql_not_work_mysql' 	=> '不工作mysql',
    'mysql_not_root_password' 	=> '无效的root密码mysql。请联系管理员',
    'mysql_user_exist' 	=> '用户存在',
    'mysql_add_db_ok' 	=> '数据库已创建',
    'mysql_add_db_exists' 	=> '存在数据库',
    'mysql_list_privilegies' 	=> '特权列表',
    'mysql_not_privilegies' 	=> '用户没有任何权限。该特权列表是空的。',
    'mysql_not_write_privilegies' 	=> '写入权限错误',
    'mysql_not_ip_parce' 	=> '无效的IP地址值。',
    'mysql_not_edit' 	=> '尝试编辑不是您的数据',

    'mysql_adddb_wrongformat' 	=> '请只使用字母a-z和数字0-9。',

    'mysql_adddb_emptypass' 	=> '请填写密码',

    'mysql_adddb_failed_overlimit' 	=> '超过了数据库的数量。最大数据库数量',

    'mysql_manage_db' 	=> 'MySQL数据库',

    'mysql_select_usermain' 	=> '选择用户',
    'mysql_listdb_user' 	=> '数据库',
    'mysql_loaddata_pleasewait' 	=> '请稍等',
    'mysql_user_notselect' 	=> '多个用户未被添加或未被选择',

    'mysql_run_isok' 	=> '运行中',
    'mysql_run_isfailed' 	=> '已停止',

    'mysql_intalling' 	=> '安装正在进行中',
    'mysql_intalling_successfully' 	=> '安装完成',

    'mysql_phpmyadmin_ver' 	=> '版本',
    'mysql_phpmyadmin_demo' 	=> '!!! PHPMYADMIN在演示版本中不可用。',
    'mysql_phpmyadmin_demo_2' 	=> '在常规版本中它将可用。',
    'mysql_message_remove_mysql' 	=> '如果删除mysql，邮件服务和邮件将不可用。',
    'mysql_message_remove_mysql_2' 	=> '在安装或重新安装mysql期间，邮件服务将被暂时禁用。',
    'mysql_message_stop_mysql' 	=> '如果你停止mysql，邮件服务将不可用。',
    'mysql_exit' 	=> '取消',
    'mysql_continue' 	=> '继续',
    'mysql_change_password' 	=> '更改密码',
    'mysql_short_password' 	=> '密码少于6个字符',
    'mysql_succecfully' 	=> '完成',
    'mysql_disabled_mysqld' 	=> 'mysqld服务关闭时无法执行此操作',
    'mysql_root_password' 	=> '根密码：',
    'mysql_root_password_show' 	=> '显示',
    'mysql_root_password_hide' 	=> '隐藏',
    'mysql_confirm_remove_user' 	=> '确认用户删除',
    'mysql_confirm_remove_db' 	=> '确认删除数据库',
    'mysql_control_db' 	=> '管理数据库服务器',
    'mysql_version' 	=> '数据库版本：',
    'mysql_control' 	=> '服务器管理',
    'mysql_status' 	=> '数据库状态：',
    'mysql_vers' 	=> '版本',
    'mysql_controm_phpmyadmin' 	=> '管理phpMyAdmin',
    'mysql_welcome' 	=> '欢迎来到',
    'mysql_autorisation' 	=> '授权',
    'mysql_user' 	=> '用户名：',
    'mysql_pass' 	=> '密码：',
    'mysql_input' 	=> '登录',
    'mysql_sintax_error' 	=> '语法错误my.cnf',
	'mysqlPhpMyAdminGetVersion' => '检查更新',
    'mysqlPhpMyAdminAvailNewVersion' => '新版本可用',
    'mysqlPhpMyAdminAvailNewVersionNot' => '已经安装了最新版本的phpMyAdmin',
    'mysqlPhpMyAdminAvailNewVersionNotIns' => '首先你需要安装',
    'mysqlPhpMyAdminNewVersionInstall' => '更新',
    'mysqlPhpMyAdminUpdateOk' => '已成功更新',
);

?>