<?php

$lang = array(
   'network_tools'		=> '网络工具',
   'network_tools_monit_connect'		=> '监控连接',
   'msg_menu_iptables'		=> 'iptables',
   'msg_menu_network'		=> '网络',
   'msg_addrules_iptables'		=> '添加新规则：',
   'btn_addrules_iptables'		=> '添加规则',
   'btn_save_iptables'		=> '保存所有更改',
   'btn_restore_iptables'		=> '恢复规则配置',
   'msg_iptables_add'		=> '添加成功',
   'msg_iptables_delete'		=> '成功删除',
   'msg_iptables_save'		=> '成功保存规则',
   'msg_iptables_restore'		=> '恢复成功',
   'command_iptables_start'		=> '开始',
   'command_iptables_stop'		=> '停止',
   'command_iptables_restart'		=> '重新启动',
   'tpl_title_connect'		=> '连接总数：',
   'tpl_title_connect_syn'		=> '处于SYN_RECEIVED状态的总连接数：',
   'tpl_title_connect_port'		=> '与选定端口的总连接数：',
   'tpl_title_net_status'		=> '上次状态：',
   'tpl_title_block_size'		=> '阻止所有连接的IP：',
   'tpl_btn_list_show_hide'		=> '显示/隐藏IP列表',
   'tpl_netstat_iptables_link'		=> '通过iptables阻止IP',
   'tpl_btn_block_size'		=> '手动运行',
   'msg_netstat_status_null'		=> '无法阻止',
   'msg_netstat_block_onlyip'		=> ' - 指定的IP被阻止',
   'msg_netstat_block_size'		=> ' - IP地址被阻止',
   'btn_run_check_start'		=> '运行脚本',
   'btn_run_check_stop'		=> '停止脚本',
   'msg_run_check_stop'		=> '停止工作',
   'btn_stop_start_log'		=> '打开/关闭 日志',
   'btn_update_log'		=> '更新日志信息',
   'msg_start_script_info'		=> '或者用句点（以秒为单位）运行脚本',
   'msg_checked_log_value'		=> '启用日志记录',
   'msg_run_script_status'		=> '脚本状态：',
   'msg_run_script_start'		=> '脚本',
   'msg_run_script_stop'		=> '不起作用',
   'msg_info_first_line'		=> '运行信息',
   'networktools_allports'		=> '全部',
   'networktools_rule_wrongformat'		=> '无效的规则格式',
   'networktools_th_name'		=> '名称',
   'networktools_th_connect'		=> '连接数量',
   'networktools_th_manage'		=> '管理',
   'networktools_delete_rules'		=> '删除规则',
   'networktools_get_list_ip'		=> '显示IP列表',
   'networktools_close_journal'		=> '关闭日志',
   'networktools_period_works_script'		=> '脚本运行期',
   'networktools_start_one'		=> '一次性运行',
   'networktools_start_timer'		=> '在计时器上运行',
   'networktools_open_journal'		=> '打开日志',
   'networktools_num_connect'		=> '连接数量',
   'networktools_not_connect'		=> '无连接',	
	
);

?>