<?php
$lang = array(
    'packet_manager2'	=> '批次管理器',
    'package_installed'		=> '安装',
    'package_working'		=> '供电',
    'package_control'		=> '管理',	
    'package_start'			=> '启动',
    'package_stop'			=> '停止',
    'package_restart'		=> '重新开始',
    'package_kill'			=> '强行停止',
    'package_autoload'		=> '启动',	
    'package_reinstall'		=> '重新安装',
    'package_delete'		=> '删除',	
    'package_setting'		=> '调',	
    'package_repare_standart_conf'		=> '恢复默认设置',	
    'package_error_parameters'		=> '参数错误',	
    'package_error_parameters_config'		=> '在配置文件中找不到此命令.',	
    'package_error_comand_os'		=> '找不到此操作系统的命令.',	
    'package_successfully'		=> '成功完成.',	
	'package_not_file_config'		=> '缺少配置文件',	
    'package_editable_conf'		=> '要编辑 ',	
    'package_manager_for_user'		=> '对于用户',	
    'package_manager_for_expert'		=> '对于专家',	
    'package_manager_save'		=> '保留',	
    'package_error_config'		=> '配置错误',	
    'package_not_file_repair_conf'		=> '找不到恢复文件.',	
    'package_confirm'		=> '确认此操作',
	
);
