<?php
$lang = array(
    'php_ini' => '配置php.ini',
    'php_ini_select_sites' => '选择网站',
    'php_ini_add_user_ini' => '添加user.ini',
    'php_ini_edit_user_ini' => '编辑user.ini',
    'php_ini_add_user_htaccess' => '添加user_htaccess',
    'php_ini_edit_user_htaccess' => '编辑user_htaccess',
    'php_ini_bridget_php' => '桥接php',
    'php_ini_php_version' => 'php版本',
    'php_ini_save' => '保存',
    'php_ini_cuccesfylly' => '应用设置',
    'php_ini_select_user' => '选择用户',
    'php_ini_not_int' => '该值必须是数字',
    'php_ini_not_switch' => '值必须是 打开 或 关闭',
    'php_ini_not_unrible' => 'PHP 5.2版本不支持桥接',
    'php_ini_remove_ini' => '删除ini文件',
    'php_ini_remove_ini_succ' => '设置文件被删除',
    'php_ini_remove_ini_not' => '没有设置文件',
    'php_ini_not_domain' => '用户没有任何网站',
    'php_ini_not_int_val' => '值必须是数字',
    'php_ini_not_char' => '该字符串包含非法字符',
    'php_ini_not_str_char' => '这个字符串是被禁止的符号',
    'php_ini_placeholder' => '默认情况下',
	
);