<?php

$lang = array(
    //client
    'tpl_c_serv_control_select_ip' => '选择 IP    ',
    'tpl_c_serv_control_select_php' => '选择PHP版本',
    'tpl_c_serv_control_all_sites' => '所有网站',
    'tpl_c_serv_control_bridge' => '桥接器',
    'tpl_c_serv_control_ver_php' => 'PHP版本',
    'tpl_c_serv_control_control' => '管理',

    //server
    'tpl_s_serv_control_php' => 'PHP    ',
    'tpl_s_serv_control_delete' => '删除',
    'tpl_s_serv_control_reinstall' => '重新安装',
    'tpl_s_serv_control_status' => '服务器状态',
    'tpl_s_serv_control_more' => '更多详情',
    'tpl_s_serv_control_hide' => '隐藏',
    'tpl_s_serv_control_choose_bridge' => '可用的桥接器',
    'tpl_s_serv_control_yes' => '是',
    'tpl_s_serv_control_no' => '否',
    'tpl_s_serv_control_available_bridges' => '可用桥接器',
    'tpl_s_serv_control_default_bridge' => '默认桥接器',
    'tpl_s_serv_control_choose_php' => '能够选择PHP版本',
    'tpl_s_serv_control_available_php' => 'PHP的可用版本',
    'tpl_s_serv_control_default_php' => '默认情况下PHP版本',
    'tpl_s_serv_control_apply' => '应用',
    'tpl_s_serv_control_save_config' => '保存当前配置',
    'tpl_s_serv_control_load_config' => '加载当前配置',
    'tpl_s_serv_control_cancel' => '取消',
    'tpl_s_serv_control_params_config' => '保存的配置参数',

    'tpl_s_serv_control_open_bridge' => '打开桥接器',
    'tpl_s_serv_control_open_php' => '开放版本的PHP',
    'tpl_s_serv_control_default_bridge' => '默认桥接器',
    'tpl_s_serv_control_default_php' => '默认PHP',
    'tpl_s_serv_control_select_bridge' => '选择桥接的可能性',
    'tpl_s_serv_control_select_php' => '能够选择PHP',

    'tpl_s_serv_control_delete_conf' => '删除保存的配置',
    'tpl_s_serv_control_action' => '操作',
    'tpl_s_serv_control_edit_php_ini' => '编辑主要的php.ini选项',
    'tpl_s_serv_control_edit_beginners' => '对于初学者',
    'tpl_s_serv_control_edit_experts' => '对于专家',
    'tpl_s_serv_control_save' => '保存',
    'tpl_s_serv_control_ver_select' => '选择版本',

    'tpl_c_serv_control_control_fpm' => '控制fpm',
    'tpl_c_serv_control_start' => '开始',
    'tpl_c_serv_control_stop' => '停止',
    'tpl_c_serv_control_restart' => '重新启动',
    'tpl_c_serv_control_force_restart' => '重新启动',

    'tpl_c_serv_control_client_options' => '客户选项',

    'tpl_c_serv_control_connect_php_php' => '包含PHP为mod_php',
    'tpl_c_serv_control_connect_php_cgi' => '将PHP包含为cgi',
    'tpl_c_serv_control_connect_php_fcgi' => '包含PHP为fcgi',
    'tpl_c_serv_control_connect_php_suphp' => '包含PHP为suphp',
    'tpl_c_serv_control_connect_php_ruid2' => '包含PHP为ruid2',
    'tpl_c_serv_control_connect_php_fpm' => '包含PHP为fpm',
    'tpl_c_serv_control_connection' => '连接',
    'tpl_c_serv_control_additions' => '添加',
    'tpl_c_serv_control_additions_connection' => '连接附加组件',

    'tpl_s_serv_control_name' => '名称',
    'tpl_s_serv_control_stat' => '状态',
    'tpl_s_serv_control_install' => '安装',
    'tpl_s_serv_control_del' => '删除',
    'tpl_s_serv_control_hookup' => '连接',
    'tpl_s_serv_control_select_all' => '全选',
    'tpl_s_serv_control_cancel_all' => '全部停用',
    'tpl_s_serv_control_connected' => '已连接',


    'tpl_s_serv_control_save_config_php' => '保存当前的php配置',
    'tpl_s_serv_control_load_config_php' => '下载当前的PHP配置',
    'tpl_s_serv_control_version_selection' => '选择版本',

    'tpl_s_serv_control_control_fpm' => '控制fpm',

    'tpl_s_serv_control_command_already_done' => '该命令已经成功执行',

    'tpl_s_serv_control_isntall_megapack' => '安装现成捆绑',
    'tpl_s_serv_control_isntall_megapack_select_webserver' => '选择Web服务器',

    'tpl_s_serv_control_isntall_megapack_select_php' => '选择php的版本',
    'server_control_mess_repo_update' => 'php扩展名列表已更新',
    'server_control_mess_repo_update_ok' => '已成功更新php扩展列表',

    'server_control_n' => 'Virtchists重建成功',
    'server_control_n_f_u' => '没有用户的数据',
    'server_control_n_f_a' => '别名字段未正确填写，请只使用字母,数字,破折号和圆点',
    'server_control_n_f_e' => '主域名中已经存在别名',
    'server_control_are' => '别名已经存在',
    'server_control_c' => 'Dir字段完成不正确，请只使用字母,数字,短划线和斜线',
    'server_control_d_f' => '域名段填写不正确，请只使用字母,数字,短划线和点',
    'server_control_d_c' => 'Dir字段应该完成',
    'server_control_dom_c' => '域名字段应该完成',
    'server_control_dom_a_f' => '别名字段填写不正确，请仅使用字母,数字,空格,分号,昏迷,短划线和点',
    'server_control_dom_a_a_e' => '别名已经存在',
    'server_control_dom_d_f_c' => '目录字段未正确填充，请只使用字母,数字,破折号和斜线',
    'server_control_dom_d_f_i' => '域名字段未正确填写，请只使用字母,数字,破折号和句号',
    'server_control_dom_d_f_s' => '目录字段必须填写',
    'server_control_dom_d_f_s_c' => '该域名必须填写',
    'server_control_i_s' => '安装成功完成',
    'server_control_i_ns' => '安装完成并显示错误',
    'server_control_i' => '安装正在进行中',
    'server_control_s_a' => '应用设置',
    'server_control_i_d' => '正在删除',
    'server_control_d_s' => '删除成功完成',
    'server_control_d_a' => '删除完成并显示错误',
    'server_control_c_o' => '选择配置保存',
    'server_control_c_d' => '保存的配置已删除',
    'server_control_o' => '正在处理',
    'server_control_i_i' => '连接中...',
    'server_control_r_h' => '虚拟主机正在重建',
    'server_control_z_v' => '查询正在运行',
    'server_control_r_o' => '编辑主要的php.ini选项',
    'server_control_f_u' => '对于用户',
    'server_control_f_e' => '对于专家',
    'server_control_s_v' => '选择版本',
    'server_control_w_s' => 'Web服务器',
    'server_control_a_2' => 'apache2.2',
    'server_control_a_24' => 'apache2.4',
    'server_control_ng' => 'nginx',
    'server_control_a_n' => 'apache2.2 + nginx',
    'server_control_a24_n' => 'apache2.4 + nginx',
    'server_control_ko' => '客户选项',
    'server_control_start' => '开始',
    'server_control_stop' => '停止',
    'server_control_restart' => '重启',
    'server_control_frestart' => '强制重启',
    'server_control_m_f' => '控制fpm',
    'server_control_s_w' => '选择版本',
    'server_control_save' => '保存',
    'server_control_r_i' => '重新安装',
    'server_control_m_d' => '默认桥：',
    'server_control_v_php' => '默认php版本：',
    'server_control_prim' => '应用',
    'server_control_s_m' => '能够选择一个桥：',
    'server_control_y' => '是',
    'server_control_no' => '否',
    'server_control_sv_php' => '能够选择php的版本：',
    'server_control_d_m' => '可用网桥：',
    'server_control_d_v_php' => '可用的php版本：',
    'server_control_i_php_m' => '将php连接为mod_php',
    'server_control_i_php_c' => '将php连接为cgi',
    'server_control_i_php_f' => '将php连接为fcgi',
    'server_control_i_php_su' => '将php连接为suphp',
    'server_control_i_php_ruid' => '将php连接为mod_ruid2',
    'server_control_i_php_fpm' => '将php连接为fpm',
    'server_control_u_cache' => '更新php扩展列表',
    'server_control_dop' => '附加组件',
    'server_control_name' => '名称',
    'server_control_status' => '状态',
    'server_control_install' => '安装',
    'server_control_del' => '删除',
    'server_control_sel_all' => '全选',
    'server_control_podcl' => '连接',
    'server_control_ins' => '已安装',
    'server_control_pod' => '已连接',
    'server_control_s_t_c' => '保存当前的php配置',
    'server_control_l_t_c' => '加载已保存的php配置',
    'server_control_i_php7' => '添加附加组件php 7.0',
    'server_control_mark_all' => '标记全部',
    'server_control_deactivate_all' => '全部停用',
    'server_control_to_applay' => '应用',
    'server_control_supl_php' => '添加php 7.0',
    'server_control_supl56' => '添加附件php 5.6',
    'server_control_supl_php56' => '添加php 5.6',
    'server_control_proceccing' => '正在处理',
    'server_control_supl55' => '附加组件php 5.5',
    'server_control_supl54' => '添加附件php 5.4',
    'server_control_supl_54' => '补充php 5.4',
    'server_control_supl53' => '添加附件php 5.3',
    'server_control_supl_53' => '添加php 5.3',
    'server_control_supl52' => '添加php 5.2加载项',
    'server_control_supl_52' => '添加php 5.2',
    'server_control_installing' => '安装正在进行中',
    'server_control_installing_s' => '安装成功',
    'server_control_installing_e' => '安装完成并显示错误',
    'server_control_d_s_e' => '域名已成功编辑',
    'server_control_s_added' => '域名已成功添加',
    'server_control_d_already' => '域名已存在',
    'server_control_not_start' => '这种类型的web服务器没有服务器状态模块',
    'server_control_s_ok' => '停止',
    'server_control_start_ok' => '正在运行',
    'server_control_domain_sus_delete' => '域名被成功删除',
    'server_control_not_version_aiab' => '版本变更不可用',
    'server_control_ability_bridg' => '选择桥的能力：',
    'server_control_ability_php' => '选择php的能力：',
    'server_control_key_loaded' => '已加载密钥',
    'server_control_csr_created' => 'CSR已创建',
    'server_control_error' => '错误',
    'server_control_error_read_file' => '读取文件时出错',
    'server_control_key_created' => '创建密钥',
    'server_control_edit' => '编辑',
    'server_control_select_bridg' => '桥梁选择：',
    'server_control_not_domain' => '找不到域名',
    'server_control_not_paf_domain' => '该域名必须填写',
    'server_control_is_not_ip' => '这个IP地址不属于你',
    'server_control_error_dir' => '更改目录目录时发生错误',
    'server_control_not_bridg' => '没有这种桥梁，可用的桥梁 - ',
    'server_control_not_php' => '没有这样的PHP版本，可用的版本是',
    'server_control_phpvers_default' => '该域名已成功编辑，Php默认是',
    'server_control_phpvers_default1' => '该域名已成功添加，Php默认是',
    'server_control_all_version' => '，可用的版本是',
    'server_control_bridg_default' => '该域名已成功编辑，默认桥接器是',
    'server_control_bridg_default1' => '该域名已成功添加，默认桥接器是',
    'server_control_not_root' => '您没有足够的权利，删除user_edit字段',
    'server_control_list_domain' => '收到域名列表',
    'server_control_email_exist' => '该域名拥有邮件账号，先删除它们',

    'server_control_error_user' => '参数错误',

    'server_control_overlimit_domains' => '网站数量达到了上限，最大数量的网站',

    'server_control_overlimit_dnz_zones' => '已达到DNS区域数量的限制，DNS区域的最大数量',
    'server_control_alias_alr_exist' => '别名已经存在',

    'server_control_label_sel_admin' => '用户名',
    'server_control_please_wait' => '请稍等',
    'server_control_pleas_wait_adding' => '等待,添加开启',

    'server_control_no_site_added' => '尚未添加的网站',
    'server_control_user_notselect' => '多个用户未被添加或未被选择',
    'server_control_seluserplease' => '请选择一个用户',
    'server_control_selversion' => '选择版本',
    'server_control_fpm_restart_all' => '在所有FPM上运行',
    'server_control_viewprogress' => '查看过程',
    'server_control_stopprogress' => '停止安装',
    'server_control_processrun' => '正在安装...',
    'server_control_warning' => '停止php安装过程可能导致php操作不正确，请确认停止过程',
    'server_control_warning_yesstop' => '停止',
    'server_control_warning_nocont' => '继续',
    'server_control_pleaseselectphp' => '选择php的版本',
    'server_control_pleaseselectphp_all_install' => '所有版本的PHP已经安装',
    'server_control_pleaseselectphp_reinstall' => '选择重新安装的PHP版本',
    'server_control_pleaseselectphp_all_reinstall' => '尚未安装php版本',

    'server_control_configsaveok' => '应用设置',
    'server_control_warning_mega' => '停止安装bundle的过程可能导致php和web服务器的错误操作，请确认停止过程',
    'server_control_extensionphptitletable' => 'PHP扩展',
    'server_control_sel_bridge' => '桥选择：',
    'server_control_demo_message' => '对不起,此操作已在演示版本中停用',
    'server_control_nothingtodel' => '选择你想要删除的内容',
    'server_control_nothingtodel_notinstall' => '没有安装任何东西，请在Web服务器选项卡上安装所需的软件包集',

    'server_control_fpm_startok' => '成功启动',
    'server_control_fpm_ok_mess' => '成功',
    'server_control_star' => '符号*仅在别名中可用',

    'server_control_confirmdeldom' => '确认删除域名',
    'server_control_confirmdeldom_withfiles' => '删除文件和域名文件夹',

    'server_control_deldomadeny' => '您没有权限删除指定的域名',

    'server_control_mod_modsec' => '管理安全模块',
    'server_control_mod_modsec_check_label' => '激活',
    'server_control_defaulthint_stat_modsec' => '未配置mod_security状态',

    'server_control_mod_modsec_stat_change' => '安全模块状态已修改',
    'server_control_mod_modsec_stat_off' => '安全模块已禁用，请联系您的服务器管理员',

    'server_controlAliasHint' => '这个字段是可选的，要输入多个别名,请用空格,换行符,逗号或;',
    'server_statLogDomains' => '域名记录状态',
    'server_control_seluserLogs' => '选择用户',
    'server_control_LogDomain' => '域名',
    'server_control_LogDomainAccess' => '访问日志',
    'server_control_LogDomainError' => '错误日志',
    'server_control_LogDomainDomainNotExist' => '用户没有域名',
    'server_control_LogDomainDomainWrongUsername' => '无效的用户名',
    'server_control_LogDomainDomainSetOk' => '记录状态已成功更改',
    'server_control_MenuStatusLog' => '管理记录状态',
    'server_control_hintLogAccess' => '记录状态access_log在 /etc/httpd/vhost_logs/domain_access 或 /etc/nginx/vhost_logs/domain_access',
    'server_control_hintLogError' => '记录状态access_log在 /etc/httpd/vhost_logs/domain_error 或 /etc/nginx/vhost_logs/domain_error',
    'server_control_logs' => '记录',
    "server_tcp_socket_err_create" => "套接字创建错误",
    "server_tcp_socket_err_conn" => "套接字连接错误",
	"server_showAll" => "全部显示",
    "server_listDomColUser" => "用户",
    "server_hintDenyEditBridgeRoot" => "编辑网桥不可用，因为为用户启用了jailphp。 您可以通过 <a target=``_blank`` href=``index.php?do=hostacc&subaction=jail``>这里</a>",
    'server_control_captionDomain' => '域',
    'server_control_captionDomainHolder' => '输入域名或别名',

);

?>
