<?php

$lang = array(
    'speedtest' => '测试服务器速度',
    'speedtest_header' => '测试服务器速度',
    'speedtest_check_btn' => '检查到达该地区的速度',
    'speedtest_choose_server' => '选择服务器',
    'closest_server' => '最近的服务器',
    'Kiev' => '基辅',
    'Ukraine' => '乌克兰',
    'Moscow' => '莫斯科',
    'Russian_Federation' => '俄罗斯联邦',
    'Petersburg' => '圣彼得堡',
    'Chelyabinsk' => '车里雅宾斯克',
    'Vladivostok' => '符拉迪沃斯托克',
    'Vilnius' => '维尔纽斯',
    'Lithuania' => '立陶宛',
    'Riga' => '里加',
    'Latvia' => '拉脱维亚',
    'Tallinn' => '塔林',
    'Estonia' => '爱沙尼亚',
    'Prague' => '布拉格',
    'Czech_Republic' => '捷克共和国',
    'Kazakhstan' => '哈萨克斯坦',
    'Astana' => '阿斯塔纳',
    'Minsk' => '明斯克',
    'Belarus' => '白俄罗斯',
    'Tashkent' => '塔什干',
    'Uzbekistan' => '乌兹别克斯坦',
    'Paris' => '巴黎',
    'France' => '法国',
    'Rome' => '罗马',
    'Italy' => '意大利',
    'London' => '伦敦',
    'Great_Britain' => '英国',
    'Amsterdam' => '阿姆斯特丹',
    'Netherlands' => '荷兰',
    'Toronto' => '多伦多',
    'Canada' => '加拿大',
    'Berlin' => '柏林',
    'Germany' => '德国',
    'Dubai' => '迪拜',
    'United_Arab_Emirates' => '阿联酋',
    'Beijing' => '北京',
    'China' => '中国',
    'New_Delhi' => '新德里',
    'India' => '印度',
    'Washington' => '华盛顿特区',
    'United_States' => '美国',
    'New_York_City' => '纽约'

);

?>