<?php
    $lang = array(
        'transfer' => '迁移帐户',
        'transfertitle' => '账户迁移',
        'transfer_denyaccess' => '没有足够的访问权限',
        'transfer_ipremote' => '要迁移的服务器或主机的IP地址',
        'transfer_typeauth' => '授权类型',
        'transfer_typeauthkey' => '授权秘钥',
        'transfer_typeauthpass' => '通过密码',
        'transfer_check_connect_remote_server' => '检查连接',
        'transfer_repo_inputkey' => '公钥',
        'transfer_repo_inputprivate' => '密钥',
        'transfer_btngeneratekey' => '生成密钥',
        'transfer_btnsaveownkey' => '保存密钥',
        'transfer_remote_login' => '登录',
        'transfer_remote_pass' => '密码',
        'transfer_start_transfer' => '开始迁移',
        'transfer_progress_area' => '进程',
        'transfer_history_area' => '转移历史记录',
        'transfer_history_login_trans' => '用户名',
        'transfer_history_ip_trans' => '在服务器上',
        'transfer_history_ip_trans_from_ip' => '从服务器',
        'transfer_history_start_time_trans' => '传输开始时间',
        'transfer_history_stat_trans' => '转移状态',
        'transfer_history_number_row' => '数字',
        'transfer_history_stat_trans_finish' => '已完成',
        'transfer_history_stat_trans_progress' => '进行中',
        'transfer_log_message_user_exist' => '恢复用户的主文件夹存在！',
        'transfer_title_type_toremote' => '将帐户转移到远程服务器',
        'transfer_title_type_fromremote' => '从远程服务器传输帐户',

        'transfer_ipremote_fromremote' => '执行传输的服务器或主机的IP地址',
        'transfer_fromremote_getlistuser' => '获取用户列表',
        'transfer_fromremote_getlistuser_empty' => '空',
        'transfer_connect_remote_failed' => '连接到远程服务器时出错',
        'transfer_connect_remote_ok' => '成功连接到远程服务器',
        'transfer_keysavenew_ok' => '密钥已成功保存',
        'transfer_viewlog' => '查看日志',

        'transfer_userlist' => '用户列表',
        'transfer_listip_remote' => '远程服务器上的IP地址列表',
        'transfer_listip_local' => '当前服务器上的ip列表',
        'transfer_listip_free' => '只显示免费的iPad',

        'transfer_togetips_connectremote' => '连接到远程服务器以获取IP列表',
        'transfer_togetuser_connectremote' => '连接到远程服务器以获取用户列表',
        'transfer_fromremote_getlistips' => '获取IP列表',

        'transfer_notselusers' => '没有用户选择迁移',
        'transfer_notselip' => '选择你想要迁移到的IP',
        'transfer_pleasewait_receive_users' => '请稍候，我们正在获取用户列表',
        'transfer_pleasewait_receive_ips' => '请稍等，IP列表正在收到',
        'transfer_incorected_type' => '类型不匹配',
        'transfer_error_user' => '你试图进入禁区',
        'transfer_invalid_ip' => '不是有效的IP',
        'transfer_succecf_remote' => '连接到远程服务器已安装',
        'transfer_nosuccecf_remote' => '连接未建立或者远程服务器上未安装BrainyCP控制面板',
        'transfer_not_remote_login_passwd' => '没有指定远程登录或密码',
        'transfer_not_remote_login_passwd_key' => '未填写ip key或登录名',
        'transfer_list_user_remote' => '从远程主机获取用户列表',
        'transfer_list_ip_remote' => '从远程主机获取IP列表',
        'transfer_request_succec' => '请求已完成',
        'transfer_not_key' => '其中一个私钥或公钥值缺失',
        'transfer_not_type_transport' => '传输类型无效',
        'transfer_not_array_users' => '用户数组未通过',
        'transfer_incorected_ip_bind' => '不是用户绑定的有效IP地址',
        'transfer_no_stream_transfer' => '没有转移',
        'transfer_status' => '完成',
        'transfer_no_stream_transfer2' => '没有转移',
        'transfer_ip_field_wrong' => '服务器或主机名的IP未正确填写',
        'transfer_history_area_empty' => '尚未有任何转移',
        'transfer_hint_attention' => '注意：目前迁移只能在安装BrainyCP控制面板的服务器之间进行',
        'transfer_startOk'=> '转移成功开始。 请等待转移过程显示在“转移历史记录”列表中。',
        'transfer_startFailedConn'=> '传输以错误结束。 无法连接到远程服务器。 授权错误.',
        'transferHintUseKeysAuth' => '使用密钥进行授权<br/> <br/> 1.生成密钥<br/> <br/> 2.在<b>远程服务器</ b>上，将包含内容的行添加到文件/用户名/ .ssh / authorized_keys Ssh-rsa公钥<br/>',

    )
?>